# Generated by Django 4.2.25 on 2025-12-24 22:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la clase', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del contenido', null=True)),
                ('categoria', models.CharField(choices=[('anatomia', 'Anatomía Radiológica'), ('fisica', 'Física de Imágenes'), ('protocolos', 'Protocolos de Estudio'), ('patologia', 'Patología por Imagen'), ('pediatria', 'Radiología Pediátrica'), ('intervencionismo', 'Intervencionismo'), ('us', 'Ultrasonido'), ('tc', 'Tomografía Computada'), ('rm', 'Resonancia Magnética'), ('caso_clinico', 'Caso Clínico'), ('revision', 'Revisión Bibliográfica'), ('otro', 'Otro')], help_text='Categoría temática de la clase', max_length=30)),
                ('archivo', cloudinary.models.CloudinaryField(help_text='Archivo de la presentación (PPT, PDF, etc.)', max_length=255, verbose_name='archivo')),
                ('archivo_thumbnail', cloudinary.models.CloudinaryField(blank=True, help_text='Miniatura de la presentación', max_length=255, null=True, verbose_name='thumbnail')),
                ('anios_dirigidos', models.JSONField(default=list, help_text='Lista de años de residencia a los que va dirigida (ej: ["R1", "R2"])')),
                ('fecha_clase', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se dictó la clase')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('visitas', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha visualizado')),
                ('es_destacada', models.BooleanField(default=False, help_text='Marcar como clase destacada')),
                ('activa', models.BooleanField(default=True, help_text='Si está activa y visible para los usuarios')),
                ('tags', models.CharField(blank=True, help_text='Tags separados por comas (ej: tórax, covid, neumonía)', max_length=200, null=True)),
                ('autor', models.ForeignKey(help_text='Residente o médico que creó la clase', on_delete=django.db.models.deletion.CASCADE, related_name='clases_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase de Residente',
                'verbose_name_plural': 'Clases de Residentes',
                'ordering': ['-fecha_clase', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Comentario o feedback sobre la clase')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_clases', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='clases_residentes.claseresidente')),
            ],
            options={
                'verbose_name': 'Comentario de Clase',
                'verbose_name_plural': 'Comentarios de Clases',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FavoritoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='clases_residentes.claseresidente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase Favorita',
                'verbose_name_plural': 'Clases Favoritas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'clase')},
            },
        ),
        migrations.AddIndex(
            model_name='claseresidente',
            index=models.Index(fields=['-fecha_clase'], name='clases_resi_fecha_c_3abb29_idx'),
        ),
        migrations.AddIndex(
            model_name='claseresidente',
            index=models.Index(fields=['categoria'], name='clases_resi_categor_b9abf6_idx'),
        ),
        migrations.AddIndex(
            model_name='claseresidente',
            index=models.Index(fields=['autor'], name='clases_resi_autor_i_25a743_idx'),
        ),
    ]
