# Generated by Django 4.2.25 on 2025-12-24 22:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseresidente',
            name='archivo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Archivo de la presentación (PPT, PDF, etc.) - OPCIONAL', max_length=255, null=True, verbose_name='archivo'),
        ),
    ]
