# Generated by Django 5.1.4 on 2026-01-24 14:05

import clases_residentes.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0002_alter_claseresidente_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseresidente',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo de la presentación (PPT, PDF, etc.) - OPCIONAL', null=True, storage=clases_residentes.storages.S3MediaStorage(), upload_to=''),
        ),
    ]
