# Generated by Django 4.2.25 on 2026-03-04 01:51

from django.db import migrations, models


def detectar_tipo_archivos_existentes(apps, schema_editor):
    """
    Detecta automáticamente el tipo de archivo para registros existentes
    basándose en la extensión del archivo.
    """
    ClaseResidente = apps.get_model('clases_residentes', 'ClaseResidente')
    
    EXTENSIONES_VIDEO = ['mp4', 'mov', 'avi', 'webm', 'mkv', 'm4v', 'flv', 'wmv']
    
    for clase in ClaseResidente.objects.all():
        if clase.archivo:
            try:
                nombre_archivo = clase.archivo.name.lower()
                extension = nombre_archivo.split('.')[-1] if '.' in nombre_archivo else ''
                
                if extension in EXTENSIONES_VIDEO:
                    clase.tipo_archivo = 'video'
                else:
                    clase.tipo_archivo = 'documento'
                
                clase.save(update_fields=['tipo_archivo'])
            except Exception:
                # Si hay error, mantener el valor default 'documento'
                pass


def reversa_tipo_archivo(apps, schema_editor):
    """
    Función reversa: resetear todos los tipos a 'documento'
    """
    ClaseResidente = apps.get_model('clases_residentes', 'ClaseResidente')
    ClaseResidente.objects.all().update(tipo_archivo='documento')


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0003_alter_claseresidente_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseresidente',
            name='tipo_archivo',
            field=models.CharField(choices=[('documento', 'Documento (PPT, PDF, etc.)'), ('video', 'Video (MP4, MOV, etc.)')], default='documento', help_text='Tipo de archivo cargado', max_length=20),
        ),
        migrations.RunPython(detectar_tipo_archivos_existentes, reversa_tipo_archivo),
    ]
