# Generated by Django 4.2.25 on 2026-03-06 01:33

import clases_residentes.storages
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0004_claseresidente_tipo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseresidente',
            name='archivo_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Archivo de video (MP4, MOV, etc.) - almacenado en Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='claseresidente',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo de presentación (PPT, PDF, etc.) - almacenado en S3', null=True, storage=clases_residentes.storages.S3MediaStorage(), upload_to=''),
        ),
    ]
