# Generated by Django 4.2.25 on 2026-03-07 21:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0005_claseresidente_archivo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjemploVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del ejemplo', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de qué muestra este ejemplo')),
                ('categoria', models.CharField(choices=[('cita_imagen', 'Citación de Imágenes'), ('bibliografia', 'Formato de Bibliografía'), ('diseno', 'Diseño Visual'), ('presentacion', 'Presentación Oral'), ('estructura', 'Estructura de Contenido')], help_text='Categoría del ejemplo', max_length=30)),
                ('imagen', cloudinary.models.CloudinaryField(help_text='Imagen que muestra el ejemplo visual', max_length=255, verbose_name='image')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = primero)')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo y visible en la guía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejemplo de Visualización',
                'verbose_name_plural': 'Ejemplos de Visualización',
                'ordering': ['orden', '-fecha_creacion'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='clases_resi_categor_157703_idx'), models.Index(fields=['orden'], name='clases_resi_orden_c145fc_idx')],
            },
        ),
    ]
