# Generated by Django 4.2.25 on 2026-03-07 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clases_residentes', '0006_ejemplovisualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoGuiaPresentaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del acceso')),
                ('user_agent', models.CharField(blank=True, help_text='User agent del navegador (para análisis de dispositivos)', max_length=255)),
                ('usuario', models.ForeignKey(help_text='Usuario que accedió a la guía', on_delete=django.db.models.deletion.CASCADE, related_name='accesos_guia_presentaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Guía de Presentaciones',
                'verbose_name_plural': 'Accesos a Guía de Presentaciones',
                'ordering': ['-fecha_acceso'],
                'indexes': [models.Index(fields=['-fecha_acceso'], name='clases_resi_fecha_a_2f86cd_idx'), models.Index(fields=['usuario', '-fecha_acceso'], name='clases_resi_usuario_5e2f79_idx')],
            },
        ),
    ]
