# Generated by Django 4.2.25 on 2026-03-07 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clases_residentes', '0007_accesoguiapresentaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de la conversación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actividad en esta conversación')),
                ('activa', models.BooleanField(default=True, help_text='Si la conversación está activa')),
                ('usuario', models.ForeignKey(help_text='Usuario que mantiene la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación con Bot',
                'verbose_name_plural': 'Conversaciones con Bot',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Bot')], help_text='Quién envió el mensaje', max_length=10)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del mensaje')),
                ('conversacion', models.ForeignKey(help_text='Conversación a la que pertenece este mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='clases_residentes.conversacionbot')),
            ],
            options={
                'verbose_name': 'Mensaje de Bot',
                'verbose_name_plural': 'Mensajes de Bot',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversacion', 'timestamp'], name='clases_resi_convers_562145_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionbot',
            index=models.Index(fields=['-fecha_actualizacion'], name='clases_resi_fecha_a_2faf5c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionbot',
            index=models.Index(fields=['usuario', '-fecha_actualizacion'], name='clases_resi_usuario_cb0adf_idx'),
        ),
    ]
