# Generated by Django 4.2.25 on 2026-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_residentes', '0008_conversacionbot_mensajebot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajebot',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo 👍'), ('negativo', 'Negativo 👎')], help_text='Valoración del usuario sobre la respuesta del bot', max_length=10, null=True),
        ),
    ]
