# Generated by Django 5.1.4 on 2025-01-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.IntegerField(unique=True)),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
