# Generated by Django 5.1.4 on 2025-01-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_del_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_medico',
            options={'verbose_name': 'Personal Médico', 'verbose_name_plural': 'Personal Médico'},
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
