# Generated by Django 5.1.4 on 2025-01-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_del_servicio', '0002_alter_personal_medico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Franja')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
            },
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=10, verbose_name='Día de la Semana')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_del_servicio.personal_medico', verbose_name='Médico')),
                ('franja_horaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_del_servicio.franjahoraria', verbose_name='Franja Horaria')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
    ]
