# Generated by Django 5.1.4 on 2025-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_del_servicio', '0003_franjahoraria_alter_personal_medico_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('DISTANCIA', 'A Distancia')], default='PRESENCIAL', max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='servicio',
            field=models.CharField(choices=[('INFORMES', 'Informes'), ('ECOGRAFIAS', 'Ecografías')], default='INFORMES', max_length=50, verbose_name='Servicio'),
        ),
    ]
