# Generated by Django 5.2.12 on 2026-09-18 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('anios_destinatarios', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CERRADO', 'Cerrado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('resultados_publicados_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('residentes_destinatarios', models.ManyToManyField(blank=True, related_name='examenes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('ENTREGADO', 'Entregado'), ('CORREGIDO', 'Corregido'), ('ANULADO', 'Anulado')], default='INICIADO', max_length=10)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resultado_publicado_en', models.DateTimeField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='evaluaciones_residentes.examen')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_examenes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('tipo', models.CharField(choices=[('OPCION_UNICA', 'Opción única')], default='OPCION_UNICA', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones_residentes.examen')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones_residentes.pregunta')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('es_correcta', models.BooleanField(default=False)),
                ('respondida_en', models.DateTimeField(auto_now=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones_residentes.intentoexamen')),
                ('opcion_elegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='evaluaciones_residentes.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='evaluaciones_residentes.pregunta')),
            ],
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='evaluacione_estado_a70b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['creador', 'estado'], name='evaluacione_creador_33771c_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoexamen',
            index=models.Index(fields=['examen', 'estado'], name='evaluacione_examen__9e6a88_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoexamen',
            index=models.Index(fields=['residente', 'estado'], name='evaluacione_residen_5dc4a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='intentoexamen',
            constraint=models.UniqueConstraint(fields=('examen', 'residente'), name='unique_intento_examen_residente'),
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('examen', 'orden'), name='unique_pregunta_orden_examen'),
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('pregunta', 'orden'), name='unique_opcion_orden_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_correcta', True)), fields=('pregunta',), name='unique_opcion_correcta_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='unique_respuesta_intento_pregunta'),
        ),
    ]
