# Generated by Django 5.2.12 on 2026-09-19 00:03

import django.db.models.deletion
import evaluaciones_residentes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='opcion',
            name='unique_opcion_correcta_pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='opcion_elegida',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=evaluaciones_residentes.storage.EvaluacionesMediaStorage(), upload_to='preguntas/'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='comentario_docente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='requiere_correccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='texto_desarrollo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='intentoexamen',
            name='estado',
            field=models.CharField(choices=[('INICIADO', 'Iniciado'), ('ENTREGADO', 'Entregado'), ('CORREGIDO', 'Corregido'), ('PENDIENTE_CORRECCION', 'Pendiente de corrección'), ('ANULADO', 'Anulado')], default='INICIADO', max_length=22),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('OPCION_UNICA', 'Opción única'), ('OPCION_MULTIPLE', 'Opción múltiple'), ('VERDADERO_FALSO', 'Verdadero o falso'), ('DESARROLLO', 'Respuesta desarrollada')], default='OPCION_UNICA', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestaopcion',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_seleccionadas', to='evaluaciones_residentes.opcion'),
        ),
        migrations.AddField(
            model_name='respuestaopcion',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_elegidas', to='evaluaciones_residentes.respuesta'),
        ),
        migrations.AddConstraint(
            model_name='respuestaopcion',
            constraint=models.UniqueConstraint(fields=('respuesta', 'opcion'), name='unique_respuesta_opcion'),
        ),
    ]
