# Generated by Django 5.2.12 on 2026-09-19 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0002_respuestaopcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='ciclo_lectivo',
            field=models.CharField(default='SIN_DEFINIR', max_length=20),
        ),
        migrations.AddField(
            model_name='examen',
            name='modo_destinatarios',
            field=models.CharField(choices=[('TODOS', 'Todos los residentes activos'), ('ANIOS', 'Uno o varios años de residencia'), ('RESIDENTES', 'Residentes específicos')], default='ANIOS', max_length=12),
        ),
        migrations.CreateModel(
            name='DestinatarioExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_residencia_al_asignar', models.CharField(max_length=2)),
                ('ciclo_lectivo', models.CharField(max_length=20)),
                ('criterio_origen', models.CharField(choices=[('TODOS', 'Todos los residentes activos'), ('ANIOS', 'Uno o varios años de residencia'), ('RESIDENTES', 'Residentes específicos')], max_length=12)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_asignados', to='evaluaciones_residentes.examen')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_examenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['examen', 'anio_residencia_al_asignar'], name='evaluacione_examen__7be269_idx'), models.Index(fields=['residente', 'ciclo_lectivo'], name='evaluacione_residen_0128e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('examen', 'residente'), name='unique_destinatario_examen_residente')],
            },
        ),
    ]
