# Generated by Django 5.2.12 on 2026-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0003_examen_ciclo_lectivo_examen_modo_destinatarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='modo_destinatarios',
            field=models.CharField(choices=[('TODOS', 'Todos los residentes activos'), ('ANIOS', 'Uno o varios años de residencia'), ('RESIDENTES', 'Residentes específicos')], default='TODOS', max_length=12),
        ),
    ]
