# Generated by Django 5.2.12 on 2026-09-19 13:34

import django.db.models.deletion
import evaluaciones_residentes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0004_alter_examen_modo_destinatarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(storage=evaluaciones_residentes.storage.EvaluacionesMediaStorage(), upload_to='preguntas/galeria/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('texto_alternativo', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='evaluaciones_residentes.pregunta')),
            ],
            options={
                'ordering': ['orden', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('pregunta', 'orden'), name='unique_pregunta_imagen_orden')],
            },
        ),
    ]
