# Generated by Django 5.2.12 on 2026-09-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0005_preguntaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='modo_inicio',
            field=models.CharField(choices=[('AUTOMATICO', 'Automático por fecha'), ('MANUAL', 'Manual por docente')], default='AUTOMATICO', max_length=12),
        ),
    ]
