# Generated by Django 5.2.12 on 2026-09-22 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0006_examen_iniciado_en_examen_modo_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoexamen',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentoexamen',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intentoexamen',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
