# Generated by Django 5.2.12 on 2026-09-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_residentes', '0007_intentoexamen_anulado_en_intentoexamen_anulado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoexamen',
            name='motivo_recuperacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intentoexamen',
            name='recuperado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentoexamen',
            name='recuperado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos_recuperados', to=settings.AUTH_USER_MODEL),
        ),
    ]
