# Generated by Django 5.1.4 on 2025-01-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion_honorarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='medicos',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='matricula',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Matrícula'),
        ),
    ]
