# Generated by Django 4.2.25 on 2026-01-16 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre identificativo del consultorio (ej: 'Eco 1', 'Eco 2')", max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, help_text="Ubicación física (ej: 'Piso 2, Ala Norte')", max_length=200, null=True)),
                ('esta_activo', models.BooleanField(default=True, help_text='¿El consultorio está actualmente operativo?')),
                ('capacidad_pacientes_hora', models.PositiveIntegerField(default=4, help_text='Capacidad estimada de pacientes por hora')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el consultorio', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del profesional', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del profesional', max_length=100)),
                ('matricula', models.CharField(help_text='Matrícula profesional (nacional o provincial)', max_length=50, unique=True)),
                ('especialidad', models.CharField(blank=True, help_text="Especialidad médica (ej: 'Ecografía', 'Radiología')", max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254, null=True)),
                ('esta_activo', models.BooleanField(default=True, help_text='¿El profesional está actualmente activo?')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el profesional', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesional Externo',
                'verbose_name_plural': 'Profesionales Externos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipoConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de la asignación')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la asignación (dejar vacío si es permanente)', null=True)),
                ('es_permanente', models.BooleanField(default=False, help_text='¿La asignación es permanente? (ignora fecha_fin)')),
                ('observaciones', models.TextField(blank=True, help_text="Notas sobre esta asignación (ej: 'Rotación por mantenimiento')", null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_equipos', to='consultorios.consultorio')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_consultorios', to='equipos.equipoimagen')),
            ],
            options={
                'verbose_name': 'Asignación Equipo-Consultorio',
                'verbose_name_plural': 'Asignaciones Equipo-Consultorio',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del bloque')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del bloque')),
                ('fecha_inicio_vigencia', models.DateField(default=django.utils.timezone.now, help_text='Fecha desde la cual este bloque está vigente')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual este bloque está vigente (vacío = indefinido)', null=True)),
                ('tipo_actividad', models.CharField(choices=[('ECO_GENERAL', 'Ecografía General'), ('ECO_DOPPLER', 'Ecografía Doppler'), ('ECO_OBSTETRICA', 'Ecografía Obstétrica'), ('ECO_PEDIATRICA', 'Ecografía Pediátrica'), ('ECO_MSK', 'Ecografía Musculoesquelética'), ('INTERV', 'Intervencionismo Ecoguiado'), ('OTRO', 'Otro')], default='ECO_GENERAL', help_text='Tipo de estudios a realizar en este bloque', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', help_text='Estado actual del bloque horario', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este bloque', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to='consultorios.consultorio')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este bloque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, help_text='Equipo específico a usar (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_horarios', to='equipos.equipoimagen')),
                ('profesional_externo', models.ForeignKey(blank=True, help_text='Profesional externo (no usuario del sistema)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to='consultorios.profesionalexterno')),
                ('profesional_interno', models.ForeignKey(blank=True, help_text='Profesional registrado en el sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['consultorio', 'dia_semana', 'estado'], name='consultorio_consult_057791_idx'), models.Index(fields=['profesional_interno', 'estado'], name='consultorio_profesi_8e38f8_idx'), models.Index(fields=['profesional_externo', 'estado'], name='consultorio_profesi_d4127d_idx')],
            },
        ),
    ]
