# Generated by Django 5.2.12 on 2026-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='competencia_requerida',
            field=models.CharField(blank=True, help_text='Competencia requerida para prestaciones especializadas', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='permite_cobertura_residente',
            field=models.BooleanField(default=False, help_text='Indica si este bloque admite cobertura por residentes'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='prioridad_cobertura',
            field=models.PositiveSmallIntegerField(default=3, help_text='Prioridad operativa de cobertura (1=alta, 5=baja)'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='tipo_lista',
            field=models.CharField(choices=[('LISTA_STAFF', 'Lista Staff'), ('LISTA_DOCENTE', 'Lista Docente como Staff'), ('LISTA_POOL', 'Lista Residente Pool'), ('LISTA_ESPEC', 'Lista Especializada')], default='LISTA_STAFF', help_text='Tipo de lista operativa para este bloque', max_length=20),
        ),
        migrations.AddField(
            model_name='profesionalexterno',
            name='categoria',
            field=models.CharField(choices=[('STAFF_EXT', 'Staff Externo'), ('CARD_EXT', 'Cardiólogo Externo'), ('OTRO_EXT', 'Otro Externo')], default='STAFF_EXT', help_text='Clasificación operativa del profesional externo', max_length=20),
        ),
    ]
