# Generated by Django 5.2.12 on 2026-05-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0002_bloquehorario_competencia_requerida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ausencia', models.DateField(help_text='Fecha puntual de la ausencia')),
                ('motivo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitación'), ('PERSONAL', 'Motivo Personal'), ('OTRO', 'Otro')], default='OTRO', help_text='Motivo principal de la ausencia', max_length=20)),
                ('detalle_motivo', models.TextField(blank=True, help_text='Detalle adicional del motivo', null=True)),
                ('estado', models.CharField(choices=[('REPORTADA', 'Reportada'), ('PROPUESTA', 'Propuesta'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='REPORTADA', help_text='Estado del circuito de ausencia/cobertura', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas operativas de la coordinación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(help_text='Bloque afectado por la ausencia', on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_cobertura', to='consultorios.bloquehorario')),
                ('profesional_ausente_externo', models.ForeignKey(blank=True, help_text='Profesional externo ausente (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_como_profesional_externo', to='consultorios.profesionalexterno')),
                ('profesional_ausente_interno', models.ForeignKey(blank=True, help_text='Profesional interno ausente (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_como_profesional_interno', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(blank=True, help_text='Usuario que reporta la ausencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_reportadas_consultorios', to=settings.AUTH_USER_MODEL)),
                ('residente_asignado', models.ForeignKey(blank=True, help_text='Residente finalmente asignado para cubrir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas_asignadas_consultorios', to=settings.AUTH_USER_MODEL)),
                ('residente_sugerido', models.ForeignKey(blank=True, help_text='Residente sugerido automáticamente por el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas_sugeridas_consultorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ausencia y Cobertura',
                'verbose_name_plural': 'Ausencias y Coberturas',
                'ordering': ['-fecha_ausencia', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_ausencia', 'estado'], name='consultorio_fecha_a_bf67f0_idx'), models.Index(fields=['residente_asignado', 'estado'], name='consultorio_residen_28b262_idx')],
                'constraints': [models.UniqueConstraint(fields=('bloque', 'fecha_ausencia'), name='unique_ausencia_por_bloque_y_fecha')],
            },
        ),
    ]
