# Generated by Django 5.2.12 on 2026-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0003_ausenciacobertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciacobertura',
            name='fecha_fin_ausencia',
            field=models.DateField(blank=True, help_text='Fecha de fin de la ausencia. Vacío = ausencia de un solo día. Si se indica, se generan registros por cada ocurrencia del día de semana del bloque dentro del rango.', null=True),
        ),
        migrations.AlterField(
            model_name='ausenciacobertura',
            name='fecha_ausencia',
            field=models.DateField(help_text='Fecha de inicio de la ausencia (o única fecha si es un día)'),
        ),
    ]
