# Generated by Django 5.2.12 on 2026-05-05 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0004_agregar_fecha_fin_ausencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAgendaEGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('HABILITAR', 'Habilitar agenda'), ('DESHABILITAR', 'Deshabilitar agenda'), ('REASIGNAR', 'Reasignar agenda a otro profesional')], help_text='Acción a realizar en EGES', max_length=20)),
                ('origen', models.CharField(choices=[('BLOQUE_NUEVO', 'Bloque nuevo creado'), ('BLOQUE_DESAC', 'Bloque desactivado/pausado'), ('BLOQUE_MOD', 'Bloque modificado (horario/profesional)'), ('AUSENCIA_SC', 'Ausencia sin cobertura'), ('AUSENCIA_CC', 'Ausencia con cobertura (reasignación)'), ('COB_CANCEL', 'Cobertura cancelada'), ('SOLIC_EXTRA', 'Solicitud de agenda extra aprobada'), ('MANUAL', 'Creada manualmente')], default='MANUAL', help_text='Evento que originó esta tarea', max_length=20)),
                ('fecha_afectada', models.DateField(blank=True, help_text='Fecha puntual afectada (ausencias, eventos únicos)', null=True)),
                ('fecha_desde', models.DateField(blank=True, help_text='Inicio del rango afectado (vacaciones, cambios de bloque)', null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fin del rango afectado', null=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Franja horaria de inicio', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Franja horaria de fin', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADO', 'Ejecutado en EGES')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Información adicional para la administrativa', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, help_text='Momento en que se marcó como ejecutado en EGES', null=True)),
                ('notas_ejecucion', models.TextField(blank=True, help_text='Notas de la administrativa al ejecutar (ej: número de agenda creada)', null=True)),
                ('consultorio', models.ForeignKey(help_text='Consultorio afectado', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_eges', to='consultorios.consultorio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_eges_creadas', to=settings.AUTH_USER_MODEL)),
                ('ejecutado_por', models.ForeignKey(blank=True, help_text='Administrativa que marcó la tarea como ejecutada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_eges_ejecutadas', to=settings.AUTH_USER_MODEL)),
                ('profesional_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_eges', to='consultorios.profesionalexterno')),
                ('profesional_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_eges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea EGES',
                'verbose_name_plural': 'Tareas EGES',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAgendaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateField(help_text='Fecha en que se solicita la agenda extra')),
                ('hora_inicio', models.TimeField(help_text='Franja horaria de inicio')),
                ('hora_fin', models.TimeField(help_text='Franja horaria de fin')),
                ('tipo_actividad', models.CharField(choices=[('ECO_GENERAL', 'Ecografía General'), ('ECO_DOPPLER', 'Ecografía Doppler'), ('ECO_OBSTETRICA', 'Ecografía Obstétrica'), ('ECO_PEDIATRICA', 'Ecografía Pediátrica'), ('ECO_MSK', 'Ecografía Musculoesquelética'), ('INTERV', 'Intervencionismo Ecoguiado'), ('OTRO', 'Otro')], default='ECO_GENERAL', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo de la solicitud de agenda extra')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_resolucion', models.TextField(blank=True, help_text='Motivo de rechazo u observaciones del jefe', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_agenda_extra', to='consultorios.consultorio')),
                ('profesional_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_extra_como_profesional', to='consultorios.profesionalexterno')),
                ('profesional_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_extra_como_profesional', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, help_text='Jefe que aprobó o rechazó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_extra_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_agenda_extra', to=settings.AUTH_USER_MODEL)),
                ('tarea_eges', models.OneToOneField(blank=True, help_text='Tarea EGES generada automáticamente al aprobar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='consultorios.tareaagendaeges')),
            ],
            options={
                'verbose_name': 'Solicitud de Agenda Extra',
                'verbose_name_plural': 'Solicitudes de Agenda Extra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='tareaagendaeges',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='consultorio_estado_6f2de4_idx'),
        ),
        migrations.AddIndex(
            model_name='tareaagendaeges',
            index=models.Index(fields=['consultorio', 'estado'], name='consultorio_consult_bbbc52_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudagendaextra',
            index=models.Index(fields=['estado', 'fecha_solicitada'], name='consultorio_estado_3e8d43_idx'),
        ),
    ]
