# Generated by Django 5.2.12 on 2026-05-06 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0005_add_tarea_eges_solicitud_extra'),
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='profesional_asignado_temporal',
            field=models.ForeignKey(blank=True, help_text='Nombre asignado para el slot genérico (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_horarios_asignacion_temporal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='tipo_titular',
            field=models.CharField(choices=[('NOMINAL', 'Nominal (profesional fijo)'), ('R2', 'Residente R2'), ('R3', 'Residente R3'), ('JEFES_RES', 'Jefes de residentes')], default='NOMINAL', help_text='Nominal (profesional fijo) o slot genérico (R2/R3/Jefes).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['tipo_titular', 'estado'], name='consultorio_tipo_ti_012733_idx'),
        ),
    ]
