# Generated by Django 5.2.12 on 2026-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0006_bloquehorario_profesional_asignado_temporal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquehorario',
            name='tipo_titular',
            field=models.CharField(choices=[('NOMINAL', 'Nominal (profesional fijo)'), ('R1', 'Residente R1'), ('R2', 'Residente R2'), ('R3', 'Residente R3'), ('R4', 'Residente R4'), ('JEFES_RES', 'Jefes de residentes')], default='NOMINAL', help_text='Nominal (profesional fijo) o slot genérico (R1-R4/Jefes).', max_length=20),
        ),
    ]
