# Generated by Django 5.1.4 on 2025-01-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franja_horaria', models.CharField(choices=[('NOCHE', '20:00 - 08:00'), ('DIA_COMPLETO', '24 horas'), ('DIA', '08:00 - 20:00'), ('NOCHE_FIN_SEMANA', '20:00 - 08:00 (Fin de semana)'), ('DIA_FIN_SEMANA', '08:00 - 20:00 (Fin de semana)')], max_length=25)),
                ('cubierta', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_guardias.medicoguardia', verbose_name='Médico')),
            ],
        ),
    ]
