# Generated by Django 5.1.4 on 2025-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('franja_horaria', models.CharField(choices=[('NOCHE', '20:00 - 08:00'), ('DIA_COMPLETO', '24 horas')], max_length=12)),
                ('cubierta', models.BooleanField(default=False)),
                ('medico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
