# Generated by Django 5.1.4 on 2025-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardia',
            name='dia_semana',
        ),
        migrations.AlterField(
            model_name='guardia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
