# Generated by Django 5.1.4 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='franja_horaria',
            field=models.CharField(choices=[('NOCHE', '20:00 - 08:00'), ('DIA_COMPLETO', '24 horas (SA-DO-FE)'), ('DIA', '08:00 - 20:00'), ('NOCHE_FIN_SEMANA', '20:00 - 08:00 (SA-DO-FE)'), ('DIA_FIN_SEMANA', '08:00 - 20:00 (SA-DO-FE)')], max_length=25),
        ),
    ]
