# Generated by Django 5.1.4 on 2025-04-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0002_alter_guardia_franja_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='cubierta',
            field=models.BooleanField(default=True),
        ),
    ]
