# Generated by Django 5.1.4 on 2025-05-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0004_medicoguardia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicoguardia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medicoguardia',
            name='nombre',
        ),
    ]
