# Generated by Django 5.1.4 on 2025-10-01 02:06
# Migración personalizada: Eliminar tablas de visor_dicom retirado

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0005_remove_medicoguardia_apellido_and_more'),
    ]

    operations = [
        # Eliminar tabla visor_dicom_dicomfile si existe
        migrations.RunSQL(
            "DROP TABLE IF EXISTS visor_dicom_dicomfile;",
            reverse_sql="-- No hay operación de reversa para esta limpieza"
        ),
    ]
