# Generated by Django 5.2.12 on 2026-04-05 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0006_auto_20250930_2306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaMensualGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_residencia', models.CharField(choices=[('R1', 'Primer año (R1)'), ('R2', 'Segundo año (R2)'), ('R3', 'Tercer año (R3)'), ('R4', 'Cuarto año (R4)'), ('R5', 'Quinto año (R5)')], max_length=10, unique=True)),
                ('guardias_por_mes', models.PositiveIntegerField(help_text='Cantidad base de guardias mensuales para este año de residencia.')),
                ('atenuante_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de reducción sobre la cuota base. Ej: 25 → la cuota efectiva es un 25% menor.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Cuota mensual de guardias',
                'verbose_name_plural': 'Cuotas mensuales de guardias',
                'ordering': ['anio_residencia'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='medicoguardia',
            name='user',
        ),
        migrations.CreateModel(
            name='AsignacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('CUMPLIDA', 'Cumplida'), ('AUSENTE', 'Ausente'), ('REASIGNADA', 'Reasignada')], default='BORRADOR', max_length=20)),
                ('es_feriado', models.BooleanField(default=False, help_text='Marcado automáticamente si la fecha coincide con un feriado registrado.')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_creadas', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(limit_choices_to={'rol': 'medico_residente'}, on_delete=django.db.models.deletion.PROTECT, related_name='guardias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de guardia',
                'verbose_name_plural': 'Asignaciones de guardias',
                'ordering': ['fecha', 'tipo_guardia'],
            },
        ),
        migrations.CreateModel(
            name='AusenciaResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de resolución'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('reportada_en', models.DateTimeField(auto_now_add=True)),
                ('guardias_afectadas', models.ManyToManyField(blank=True, related_name='ausencias', to='control_guardias.asignacionguardia')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ausencia de residente',
                'verbose_name_plural': 'Ausencias de residentes',
                'ordering': ['-reportada_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTipoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_semana', models.CharField(help_text='Días aplicables separados por coma. Valores: L,M,X,J,V,S,D', max_length=20)),
                ('aplica_feriados', models.BooleanField(default=False, help_text='Si está activo, este tipo de guardia también aplica en feriados.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_guardia_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de guardia',
                'verbose_name_plural': 'Tipos de guardia',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='asignacionguardia',
            name='tipo_guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='control_guardias.configuraciontipoguardia'),
        ),
        migrations.CreateModel(
            name='SolicitudCambioGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE_RECEPTOR', 'Esperando aceptación del receptor'), ('PENDIENTE_JEFE', 'Esperando validación de jefe/instructor'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el solicitante')], default='PENDIENTE_RECEPTOR', max_length=30)),
                ('notas_solicitante', models.TextField(blank=True)),
                ('notas_jefe', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('guardia_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_como_destino', to='control_guardias.asignacionguardia')),
                ('guardia_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_como_origen', to='control_guardias.asignacionguardia')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_recibidos', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_revisados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de guardia',
                'verbose_name_plural': 'Solicitudes de cambio de guardia',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Nueva guardia asignada'), ('PUBLICACION', 'Guardias del mes publicadas'), ('CAMBIO_SOLICITADO', 'Solicitud de cambio recibida'), ('CAMBIO_ACEPTADO', 'Tu propuesta de cambio fue aceptada'), ('CAMBIO_APROBADO', 'Cambio aprobado por jefe/instructor'), ('CAMBIO_RECHAZADO', 'Cambio rechazado'), ('AUSENCIA_RESUELTA', 'Tu ausencia fue procesada'), ('GUARDIA_REASIGNADA', 'Una de tus guardias fue reasignada')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='control_guardias.asignacionguardia')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_guardias', to=settings.AUTH_USER_MODEL)),
                ('solicitud_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='control_guardias.solicitudcambioguardia')),
            ],
            options={
                'verbose_name': 'Notificación de guardia',
                'verbose_name_plural': 'Notificaciones de guardias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Guardia',
        ),
        migrations.DeleteModel(
            name='MedicoGuardia',
        ),
        migrations.AddConstraint(
            model_name='asignacionguardia',
            constraint=models.UniqueConstraint(fields=('residente', 'fecha', 'tipo_guardia'), name='unique_residente_fecha_tipo'),
        ),
    ]
