# Generated by Django 5.2.12 on 2026-04-13 19:01

import control_guardias.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0007_cuotamensualguardia_feriado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciaresidente',
            name='certificado',
            field=models.FileField(blank=True, help_text='Adjuntar certificado (imagen, PDF o documento).', null=True, upload_to=control_guardias.models.upload_certificado_ausencia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx', 'heic', 'heif'])]),
        ),
    ]
