# Generated by Django 5.2.12 on 2026-04-13 19:55

import control_guardias.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0008_ausenciaresidente_certificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Documento respaldatorio adjunto a la ausencia.', upload_to=control_guardias.models.upload_documento_ausencia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx', 'heic', 'heif'])])),
                ('tipo_documento', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('ESTUDIO', 'Estudio/Informe'), ('NOTA', 'Nota administrativa'), ('OTRO', 'Otro')], default='CERTIFICADO', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ausencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='control_guardias.ausenciaresidente')),
            ],
            options={
                'verbose_name': 'Documento de ausencia',
                'verbose_name_plural': 'Documentos de ausencias',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
