# Generated by Django 5.2.12 on 2026-04-24 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_guardias', '0009_alter_cuotamensualguardia_anio_residencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotamensualguardia',
            name='anio_residencia',
            field=models.CharField(choices=[('R1', 'Primer año (R1)'), ('R2', 'Segundo año (R2)'), ('R3', 'Tercer año (R3)'), ('R4', 'Cuarto año (R4)')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='AjusteCuotaGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes al que aplica el ajuste (1-12).')),
                ('anio', models.PositiveIntegerField(help_text='Año al que aplica el ajuste.')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Guardias adicionales que se suman a la cuota base del residente para ese mes.')),
                ('tipo', models.CharField(choices=[('CARRYOVER', 'Traslado del mes anterior'), ('PENALIZACION', 'Guardia extra por penalización')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_cuota_creados', to=settings.AUTH_USER_MODEL)),
                ('guardia_origen', models.ForeignKey(blank=True, help_text='Guardia que originó este ajuste (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajuste_cuota_generado', to='control_guardias.asignacionguardia')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_cuota_guardias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de cuota de guardia',
                'verbose_name_plural': 'Ajustes de cuota de guardias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RotacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Rotación Clínica Médica HIBA', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ignorar esta rotación sin eliminarla del historial.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_externas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rotación externa',
                'verbose_name_plural': 'Rotaciones externas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSlotVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_fecha', models.DateField(help_text='Fecha del slot vacante destino (día Y).')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el solicitante')], default='PENDIENTE', max_length=20)),
                ('notas_solicitante', models.TextField(blank=True)),
                ('notas_jefe', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('guardia_ceder', models.ForeignKey(help_text='Guardia que el residente cede (día X).', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_slot_vacante_origen', to='control_guardias.asignacionguardia')),
                ('guardia_creada', models.ForeignKey(blank=True, help_text='AsignacionGuardia creada al aprobar (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_slot_vacante_origen', to='control_guardias.asignacionguardia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots_vacantes_revisados', to=settings.AUTH_USER_MODEL)),
                ('slot_tipo_guardia', models.ForeignKey(help_text='Tipo del slot vacante destino.', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_slot_vacante', to='control_guardias.configuraciontipoguardia')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_slot_vacante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de slot vacante',
                'verbose_name_plural': 'Solicitudes de slot vacante',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
