# Generated by Django 5.2.12 on 2026-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='inbox-principal', max_length=255)),
                ('proveedor', models.CharField(default='IMAP', max_length=20)),
                ('estado', models.CharField(choices=[('OK', 'Correcta'), ('ERROR', 'Con error'), ('SIN_CONFIG', 'Sin configurar')], default='OK', max_length=20)),
                ('mensaje', models.CharField(blank=True, max_length=255)),
                ('correos_leidos', models.PositiveIntegerField(default=0)),
                ('correos_nuevos', models.PositiveIntegerField(default=0)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sincronización de correo',
                'verbose_name_plural': 'Sincronizaciones de correo',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='CorreoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='inbox-principal', max_length=255)),
                ('proveedor', models.CharField(default='IMAP', max_length=20)),
                ('remote_uid', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('remitente', models.CharField(blank=True, max_length=255)),
                ('remitente_nombre', models.CharField(blank=True, max_length=255)),
                ('asunto', models.CharField(max_length=500)),
                ('fecha_email', models.DateTimeField()),
                ('snippet', models.TextField(blank=True)),
                ('cuerpo_texto', models.TextField(blank=True)),
                ('leido', models.BooleanField(default=False)),
                ('tiene_adjuntos', models.BooleanField(default=False)),
                ('cantidad_adjuntos', models.PositiveIntegerField(default=0)),
                ('score_importancia', models.PositiveSmallIntegerField(default=0)),
                ('prioridad_sugerida', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('NORMAL', 'Normal'), ('BAJA', 'Baja')], default='NORMAL', max_length=10)),
                ('categoria', models.CharField(choices=[('DIRECCION', 'Dirección'), ('AUDITORIA', 'Auditoría'), ('SOPORTE', 'Soporte'), ('OPERATIVO', 'Operativo'), ('RRHH', 'RRHH'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('requiere_accion', models.BooleanField(default=False)),
                ('resumen_ejecutivo', models.CharField(blank=True, max_length=280)),
                ('resumen_ia', models.TextField(blank=True)),
                ('acciones_sugeridas', models.JSONField(blank=True, default=list)),
                ('datos_raw', models.JSONField(blank=True, default=dict)),
                ('sincronizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correo resumido',
                'verbose_name_plural': 'Correos resumidos',
                'ordering': ['-fecha_email', '-score_importancia'],
                'indexes': [models.Index(fields=['-fecha_email'], name='correo_resu_fecha_e_bd5e60_idx'), models.Index(fields=['leido', 'score_importancia'], name='correo_resu_leido_20e868_idx'), models.Index(fields=['prioridad_sugerida'], name='correo_resu_priorid_b0963c_idx')],
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'message_id'), name='correo_resumen_unique_cuenta_message_id')],
            },
        ),
    ]
