# Generated by Django 5.2.12 on 2026-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo_resumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoresumen',
            name='estado_atencion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='correoresumen',
            name='evidencia_fecha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correoresumen',
            name='fecha_compromiso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correoresumen',
            name='requiere_respuesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='correoresumen',
            index=models.Index(fields=['requiere_respuesta', 'estado_atencion', '-fecha_email'], name='correo_resu_requier_dfe8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='correoresumen',
            index=models.Index(fields=['fecha_compromiso', 'estado_atencion'], name='correo_resu_fecha_c_be615c_idx'),
        ),
    ]
