# Generated by Django 5.2.12 on 2026-04-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo_resumen', '0002_correoresumen_estado_atencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoHilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(default='inbox-principal', max_length=255)),
                ('asunto_normalizado', models.CharField(db_index=True, max_length=500)),
                ('participantes', models.JSONField(blank=True, default=dict)),
                ('fecha_primer_email', models.DateTimeField()),
                ('fecha_ultimo_email', models.DateTimeField()),
                ('resumen_hilo', models.TextField(blank=True)),
                ('prioridad_hilo', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('NORMAL', 'Normal'), ('BAJA', 'Baja')], default='NORMAL', max_length=10)),
                ('estado_hilo', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('requiere_respuesta', models.BooleanField(default=False)),
                ('fecha_compromiso', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('correos', models.ManyToManyField(related_name='hilo', to='correo_resumen.correoresumen')),
            ],
            options={
                'verbose_name': 'Hilo de correo',
                'verbose_name_plural': 'Hilos de correo',
                'ordering': ['-fecha_ultimo_email', '-prioridad_hilo'],
                'indexes': [models.Index(fields=['cuenta', 'asunto_normalizado'], name='correo_resu_cuenta_f1c7cd_idx'), models.Index(fields=['estado_hilo', '-fecha_ultimo_email'], name='correo_resu_estado__4da43a_idx'), models.Index(fields=['requiere_respuesta', 'estado_hilo'], name='correo_resu_requier_6be9d7_idx'), models.Index(fields=['fecha_compromiso', 'estado_hilo'], name='correo_resu_fecha_c_a55eab_idx')],
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'asunto_normalizado'), name='correo_hilo_unique_cuenta_asunto')],
            },
        ),
    ]
