# Generated by Django 5.2.12 on 2026-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo_resumen', '0003_correohilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='correohilo',
            name='fecha_seguimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='correohilo',
            index=models.Index(fields=['fecha_seguimiento', 'estado_hilo'], name='correo_resu_fecha_s_25d176_idx'),
        ),
    ]
