# Generated by Django 5.2.12 on 2026-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo_resumen', '0004_correohilo_fecha_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correohilo',
            name='resumen_ia_generado',
            field=models.BooleanField(default=False),
        ),
    ]
