# Generated by Django 5.1.4 on 2025-01-11 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('TOMOGRAFIA', 'Tomografía'), ('RESONANCIA', 'Resonancia Magnética'), ('RADIOGRAFIA', 'Radiografía'), ('ECOGRAFIA', 'Ecografía')], max_length=50)),
                ('regiones', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='TarifaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('TOMOGRAFIA', 'Tomografía'), ('RESONANCIA', 'Resonancia Magnética'), ('RADIOGRAFIA', 'Radiografía'), ('ECOGRAFIA', 'Ecografía')], max_length=50)),
                ('valor_por_region', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tarifa Estudio',
                'verbose_name_plural': 'Tarifas Estudios',
            },
        ),
        migrations.CreateModel(
            name='DetalleRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.estudio')),
            ],
            options={
                'verbose_name': 'Detalle de Registro',
                'verbose_name_plural': 'Detalles de Registro',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_regiones', models.PositiveIntegerField(default=0, editable=False)),
                ('estudios', models.ManyToManyField(through='liquidacion.DetalleRegistro', to='liquidacion.estudio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.medico')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
            },
        ),
        migrations.AddField(
            model_name='detalleregistro',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.registrodiario'),
        ),
    ]
