# Generated by Django 5.1.4 on 2025-01-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_paciente_registrodiario_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifaEstudio',
        ),
        migrations.AlterModelOptions(
            name='detalleregistro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrodiario',
            options={},
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='estudios',
        ),
        migrations.AlterField(
            model_name='detalleregistro',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleregistro',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='liquidacion.registrodiario'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='regiones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidacion.paciente'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='total_regiones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
