# Generated by Django 5.1.4 on 2025-01-13 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_delete_tarifaestudio_alter_detalleregistro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Estudio'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.medico', verbose_name='Médico'),
        ),
    ]
