# Generated by Django 5.1.4 on 2025-01-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0004_alter_registrodiario_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistro',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='detalleregistro',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='DetalleRegistro',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='RegistroDiario',
        ),
    ]
