# Generated by Django 5.1.4 on 2025-01-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0007_alter_medico_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estudio')),
                ('tipo', models.CharField(choices=[('ECO', 'Ecografía'), ('RAD', 'Radiografía'), ('TOM', 'Tomografía'), ('RES', 'Resonancia Magnética')], default='ECO', max_length=3, verbose_name='Tipo de estudio')),
                ('conteo_regiones', models.IntegerField(verbose_name='Cantidad de regiones')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
            },
        ),
    ]
