# Generated by Django 5.1.4 on 2025-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0008_estudios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del estudio'),
        ),
    ]
