# Generated by Django 5.1.4 on 2025-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0010_registroestudiospormedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroestudiospormedico',
            name='estudio',
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='estudio',
            field=models.ManyToManyField(to='liquidacion.estudios', verbose_name='Estudios'),
        ),
    ]
