# Generated by Django 5.1.4 on 2025-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0011_remove_registroestudiospormedico_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='dni_paciente',
            field=models.CharField(verbose_name='DNI del paciente'),
        ),
    ]
