# Generated by Django 5.1.4 on 2025-01-31 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0012_alter_registroestudiospormedico_dni_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProcedimientosIntervensionismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=50, verbose_name='Nombre del paciente')),
                ('apellido_paciente', models.CharField(max_length=50, verbose_name='Apellido del paciente')),
                ('dni_paciente', models.CharField(max_length=50, verbose_name='DNI del paciente')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('fecha_del_procedimiento', models.DateField(blank=True, null=True, verbose_name='Fecha del procedimiento')),
                ('procedimiento', models.CharField(max_length=150, verbose_name='Procedimiento realizado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Registro de procedimiento de intervencionismo',
                'verbose_name_plural': 'Registros de procedimientos de intervencionismo',
            },
        ),
    ]
