# Generated by Django 5.1.4 on 2025-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0013_registroprocedimientosintervensionismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprocedimientosintervensionismo',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI del paciente'),
        ),
    ]
