# Generated by Django 5.1.4 on 2025-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0014_alter_registroprocedimientosintervensionismo_dni_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroprocedimientosintervensionismo',
            name='conteo_regiones',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de regiones'),
        ),
    ]
