# Generated by Django 5.1.4 on 2025-02-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0016_alter_registroestudiospormedico_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='cantidad_estudio',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad por estudio'),
        ),
    ]
