# Generated by Django 5.1.4 on 2025-02-10 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0017_registroestudiospormedico_cantidad_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='fecha_del_informe',
            field=models.DateField(verbose_name='Fecha del informe'),
        ),
        migrations.AlterField(
            model_name='registroprocedimientosintervensionismo',
            name='fecha_del_procedimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del procedimiento'),
        ),
    ]
