# Generated by Django 5.1.4 on 2025-03-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0018_alter_registroestudiospormedico_fecha_del_informe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSinPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha sin pacientes')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación (opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_sin_pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Día sin pacientes',
                'verbose_name_plural': 'Días sin pacientes',
                'ordering': ['-fecha'],
                'unique_together': {('medico', 'fecha')},
            },
        ),
    ]
