# Generated by Django 5.1.4 on 2025-03-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0019_diasinpacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasinpacientes',
            name='registrado_por',
        ),
    ]
