# Generated by Django 5.1.4 on 2025-05-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0020_remove_diasinpacientes_registrado_por'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
