# Generated by Django 4.2.25 on 2025-12-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0021_delete_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='dni_paciente',
            field=models.CharField(max_length=20, verbose_name='DNI del paciente'),
        ),
    ]
