# Generated by Django 5.1.4 on 2026-02-16 22:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0022_alter_registroestudiospormedico_dni_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudios',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.AlterModelOptions(
            name='registroestudiospormedico',
            options={'ordering': ['-fecha_del_informe', '-fecha_registro'], 'verbose_name': 'Registro de estudio por médico', 'verbose_name_plural': 'Registros de estudios por médico'},
        ),
        migrations.AlterModelOptions(
            name='registroprocedimientosintervensionismo',
            options={'managed': True, 'verbose_name': '[DESHABILITADO] Registro de procedimiento de intervencionismo', 'verbose_name_plural': '[DESHABILITADO] Registros de procedimientos de intervencionismo'},
        ),
        migrations.AddField(
            model_name='estudios',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para ocultar en formularios', verbose_name='Estudio Activo'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ej: 902225, 901244', max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='conteo_regiones_default',
            field=models.PositiveIntegerField(default=1, help_text='Valor por defecto que aparece en el formulario', verbose_name='Regiones (default en formulario)'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='fecha_actualizacion_precios',
            field=models.DateField(auto_now=True, verbose_name='Última actualización de precios'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='precio_cober',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio para obra social COBER', max_digits=10, verbose_name='Precio COBER'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='precio_otras_os',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio para otras obras sociales', max_digits=10, verbose_name='Precio OTRAS OS'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='precio_unico',
            field=models.BooleanField(default=False, help_text='Si True, precio_cober = precio_otras_os. Ej: TAC, RMN, RX', verbose_name='Precio Único'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='cantidad_regiones',
            field=models.PositiveIntegerField(default=1, help_text='Solo números enteros, no se fraccionan', verbose_name='Cantidad de Regiones'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='fecha_hora_informe',
            field=models.DateTimeField(blank=True, help_text='Cuándo se entregó el informe (para calcular urgencia)', null=True, verbose_name='Fecha/Hora Informe'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='fecha_hora_solicitud',
            field=models.DateTimeField(blank=True, help_text='Cuándo se solicitó el estudio (para calcular urgencia)', null=True, verbose_name='Fecha/Hora Solicitud'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='horario',
            field=models.CharField(blank=True, choices=[('INTRA', 'Intra Residencia (50%)'), ('EXTRA', 'Extra Residencia (100%)'), ('NA', 'No Aplica (Staff)')], default='NA', max_length=6, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='monto_calculado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se calcula automáticamente al guardar', max_digits=10, verbose_name='Monto Calculado'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='motivo_modificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='paciente_internado',
            field=models.BooleanField(default=False, help_text='Marca si el paciente estaba internado al momento del estudio', verbose_name='Paciente Internado'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='tipo_obra_social',
            field=models.CharField(blank=True, choices=[('COBER', 'COBER'), ('OTRAS_OS', 'Otras Obras Sociales')], default='OTRAS_OS', max_length=10, verbose_name='Tipo de Obra Social'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='conteo_regiones',
            field=models.IntegerField(help_text='Cantidad de regiones estándar para este estudio', verbose_name='Cantidad de regiones'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='tipo',
            field=models.CharField(choices=[('ECO', 'Ecografía'), ('RAD', 'Radiografía'), ('TOM', 'Tomografía'), ('RES', 'Resonancia Magnética'), ('DOP', 'Doppler'), ('MAM', 'Mamografía')], default='ECO', max_length=3, verbose_name='Tipo de estudio'),
        ),
        migrations.CreateModel(
            name='HistorialPrecioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cober_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio COBER Anterior')),
                ('precio_otras_os_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio OTRAS OS Anterior')),
                ('precio_cober_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio COBER Nuevo')),
                ('precio_otras_os_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio OTRAS OS Nuevo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('motivo_actualizacion', models.TextField(blank=True, help_text='Ej: Negociación anual, Ajuste por inflación, etc.', verbose_name='Motivo')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='liquidacion.estudios', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='SesionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(help_text='1-12', verbose_name='Mes')),
                ('año', models.PositiveIntegerField(help_text='2020-2050', verbose_name='Año')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta - Médicos pueden registrar'), ('REVISION', 'En Revisión - Cierre preliminar'), ('CERRADA', 'Cerrada - Solo Admin puede cargar faltantes'), ('FACTURADA', 'Facturada - Montos calculados y definitivos'), ('PAGADA', 'Pagada - Profesionales cobraron')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
            ],
            options={
                'verbose_name': 'Sesión Contable',
                'verbose_name_plural': 'Sesiones Contables',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='GuardiaPasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardia', models.DateField(help_text='Día que el médico estuvo de guardia pasiva', verbose_name='Fecha de Guardia')),
                ('tipo_guardia', models.CharField(choices=[('COBER', 'COBER'), ('OTRAS_OS', 'Otras Obras Sociales')], default='COBER', max_length=10, verbose_name='Tipo de Guardia')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('36500.00'), help_text='Valor fijo de la guardia pasiva', max_digits=10, verbose_name='Monto por Día')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardias_pasivas', to='liquidacion.sesioncontable', verbose_name='Sesión Contable')),
            ],
            options={
                'verbose_name': 'Guardia Pasiva',
                'verbose_name_plural': 'Guardias Pasivas',
                'ordering': ['-fecha_guardia'],
            },
        ),
        migrations.AddField(
            model_name='diasinpacientes',
            name='sesion_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_sin_pacientes', to='liquidacion.sesioncontable', verbose_name='Sesión Contable'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='sesion_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='liquidacion.sesioncontable', verbose_name='Sesión Contable'),
        ),
        migrations.AddIndex(
            model_name='registroestudiospormedico',
            index=models.Index(fields=['sesion_contable', 'medico'], name='liquidacion_sesion__85ebe4_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestudiospormedico',
            index=models.Index(fields=['fecha_del_informe'], name='liquidacion_fecha_d_21cc21_idx'),
        ),
        migrations.AddIndex(
            model_name='historialprecioestudio',
            index=models.Index(fields=['estudio', '-fecha_actualizacion'], name='liquidacion_estudio_cd7c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sesioncontable',
            unique_together={('mes', 'año')},
        ),
        migrations.AddIndex(
            model_name='guardiapasiva',
            index=models.Index(fields=['sesion_contable', 'medico'], name='liquidacion_sesion__3ad386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardiapasiva',
            unique_together={('medico', 'fecha_guardia')},
        ),
    ]
