# Generated by Django 4.2.25 on 2026-02-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0023_alter_estudios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='tipo',
            field=models.CharField(choices=[('ECO', 'Ecografía'), ('RAD', 'Radiografía'), ('TOM', 'Tomografía'), ('RES', 'Resonancia Magnética'), ('DOP', 'Doppler'), ('MAM', 'Mamografía'), ('ECOCAR', 'Ecocardiograma')], default='ECO', max_length=6, verbose_name='Tipo de estudio'),
        ),
    ]
