# Generated by Django 4.2.25 on 2026-03-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0024_alter_estudios_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroestudiospormedico',
            name='cantidad_estudio',
        ),
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='cantidad_regiones',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas regiones/veces realizaste este estudio (ej: 1 tórax = 1 región, ambas rodillas = 2 regiones)', verbose_name='Cantidad de Regiones'),
        ),
        migrations.RemoveField(
            model_name='registroestudiospormedico',
            name='estudio',
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='liquidacion.estudios', verbose_name='Estudio'),
        ),
    ]
