# Generated by Django 4.2.25 on 2026-03-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0025_remove_registroestudiospormedico_cantidad_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='liquidacion.estudios', verbose_name='Estudio'),
        ),
    ]
