# Generated by Django 4.2.25 on 2026-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0026_alter_registroestudiospormedico_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudiospormedico',
            name='cantidad_regiones',
            field=models.PositiveIntegerField(default=1, help_text='Se calcula automáticamente sumando las regiones de todos los estudios seleccionados', verbose_name='Cantidad de Regiones'),
        ),
        migrations.RemoveField(
            model_name='registroestudiospormedico',
            name='estudio',
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='estudio',
            field=models.ManyToManyField(help_text='Selecciona todos los estudios realizados a este paciente', related_name='registros', to='liquidacion.estudios', verbose_name='Estudios'),
        ),
    ]
