# Generated by Django 4.2.25 on 2026-03-01 18:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_m2m_to_through(apps, schema_editor):
    """
    Migra los datos de la tabla M2M antigua a la nueva tabla intermedia.
    Todos los registros existentes tendrán cantidad=1 por defecto.
    """
    RegistroEstudiosPorMedico = apps.get_model('liquidacion', 'RegistroEstudiosPorMedico')
    RegistroEstudio = apps.get_model('liquidacion', 'RegistroEstudio')
    
    # Obtener el nombre de la tabla M2M antigua
    # Django la nombra como: liquidacion_registroestudiospormedico_estudio
    db_alias = schema_editor.connection.alias
    
    # Usar el ORM hasta que se cambie la estructura
    # Necesitamos leer de la tabla M2M antigua antes de que Django la elimine
    with schema_editor.connection.cursor() as cursor:
        # Leer todas las relaciones M2M existentes
        cursor.execute("""
            SELECT registroestudiospormedico_id, estudios_id
            FROM liquidacion_registroestudiospormedico_estudio
        """)
        
        rows = cursor.fetchall()
        
        # Crear las entradas en la nueva tabla intermedia
        registro_estudios = []
        for registro_id, estudio_id in rows:
            registro_estudios.append(
                RegistroEstudio(
                    registro_id=registro_id,
                    estudio_id=estudio_id,
                    cantidad=1  # Valor por defecto para datos migrados
                )
            )
        
        # Insertar en lotes
        if registro_estudios:
            RegistroEstudio.objects.bulk_create(registro_estudios)
            print(f"✓ Migrados {len(registro_estudios)} registros de estudios con cantidad=1")


def reverse_migration(apps, schema_editor):
    """
    No hacemos nada en el reverse - Django recreará la tabla M2M automáticamente
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0027_revert_fk_to_m2m'),
    ]

    operations = [
        # Paso 1: Crear el nuevo modelo intermedio
        migrations.CreateModel(
            name='RegistroEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Número de veces que se realizó este estudio (ej: 2 para bilateral)', verbose_name='Cantidad')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='liquidacion.estudios', verbose_name='Estudio')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Estudio por Registro',
                'verbose_name_plural': 'Estudios por Registro',
                'db_table': 'liquidacion_registro_estudio',
                'ordering': ['fecha_agregado'],
                'unique_together': {('registro', 'estudio')},
            },
        ),
        # Paso 2: Migrar datos de la tabla M2M antigua a la nueva tabla intermedia
        migrations.RunPython(migrate_m2m_to_through, reverse_migration),
        # Paso 3: Remover el campo M2M antiguo
        migrations.RemoveField(
            model_name='registroestudiospormedico',
            name='estudio',
        ),
        # Paso 4: Crear el nuevo campo M2M con through
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='estudio',
            field=models.ManyToManyField(
                help_text='Selecciona todos los estudios realizados a este paciente',
                related_name='registros',
                through='liquidacion.RegistroEstudio',
                to='liquidacion.estudios',
                verbose_name='Estudios'
            ),
        ),
    ]
