# Generated by Django 5.2.12 on 2026-05-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0029_add_sesion_contable_estado_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: TC_SIMPLE, TC_CONTRASTE, DOPPLER_CARDIACO_LECHO', max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('modalidad', models.CharField(choices=[('ECO', 'Ecografía'), ('RAD', 'Radiografía'), ('TOM', 'Tomografía'), ('RES', 'Resonancia Magnética')], max_length=3, verbose_name='Modalidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo Tarifario',
                'verbose_name_plural': 'Grupos Tarifarios',
                'ordering': ['modalidad', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='estudios',
            name='grupo_tarifario',
            field=models.ForeignKey(blank=True, help_text='Grupo de facturación para cálculo por tarifas vigentes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='liquidacion.grupotarifario', verbose_name='Grupo tarifario'),
        ),
        migrations.CreateModel(
            name='TarifaGrupoTarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField(verbose_name='Vigencia desde')),
                ('vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigencia hasta')),
                ('precio_cober', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio COBER')),
                ('precio_otras_os', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio OTRAS OS')),
                ('motivo_actualizacion', models.TextField(blank=True, verbose_name='Motivo de actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas_grupo_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('grupo_tarifario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='liquidacion.grupotarifario', verbose_name='Grupo tarifario')),
            ],
            options={
                'verbose_name': 'Tarifa de Grupo Tarifario',
                'verbose_name_plural': 'Tarifas de Grupos Tarifarios',
                'ordering': ['grupo_tarifario', '-vigencia_desde'],
                'indexes': [models.Index(fields=['grupo_tarifario', 'vigencia_desde'], name='liquidacion_grupo_t_e84ffe_idx'), models.Index(fields=['vigencia_desde', 'vigencia_hasta'], name='liquidacion_vigenci_25c494_idx')],
                'constraints': [models.UniqueConstraint(fields=('grupo_tarifario', 'vigencia_desde'), name='uq_tarifa_grupo_vigencia_desde')],
            },
        ),
    ]
