# Generated by Django 5.2.12 on 2026-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0030_grupotarifario_estudios_grupo_tarifario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='tiene_contexto_ubicacion',
            field=models.BooleanField(default=False, help_text='Si True, el médico puede indicar si el estudio fue en Servicio, Lecho o Quirófano (ej: Doppler, ETE)', verbose_name='Requiere contexto de ubicación'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='contexto',
            field=models.CharField(choices=[('SERVICIO', 'Consultorio / Servicio'), ('LECHO', 'En Lecho'), ('QUIROFANO', 'Quirófano')], default='SERVICIO', help_text='Indica si el estudio fue en Servicio (consultorio), en Lecho (cama del paciente) o en Quirófano', max_length=10, verbose_name='Contexto de ubicación'),
        ),
        migrations.AlterField(
            model_name='grupotarifario',
            name='modalidad',
            field=models.CharField(choices=[('ECO', 'Ecografía'), ('RAD', 'Radiografía'), ('TOM', 'Tomografía'), ('RES', 'Resonancia Magnética'), ('DOP', 'Doppler'), ('ECOCAR', 'Ecocardiograma')], max_length=6, verbose_name='Modalidad'),
        ),
    ]
