# Generated by Django 5.2.12 on 2026-05-17 20:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0031_registroestudio_contexto_estudios_tiene_contexto_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiapasiva',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('36500.00'), help_text='Valor histórico guardado por guardia; se fija desde la configuración vigente.', max_digits=10, verbose_name='Monto por Día'),
        ),
        migrations.CreateModel(
            name='ConfiguracionGuardiaPasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_vigente', models.DecimalField(decimal_places=2, help_text='Valor actual definido por administración para nuevas guardias.', max_digits=10, verbose_name='Monto vigente')),
                ('vigente_desde', models.DateField(help_text='Fecha desde la cual rige este valor.', verbose_name='Vigente desde')),
                ('motivo_actualizacion', models.TextField(blank=True, help_text='Detalle del cambio para trazabilidad.', verbose_name='Motivo de actualización')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_guardia_pasiva_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Guardia Pasiva',
                'verbose_name_plural': 'Configuración de Guardia Pasiva',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialConfiguracionGuardiaPasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto anterior')),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto nuevo')),
                ('vigente_desde_anterior', models.DateField(verbose_name='Vigente desde anterior')),
                ('vigente_desde_nueva', models.DateField(verbose_name='Vigente desde nueva')),
                ('motivo_actualizacion', models.TextField(blank=True, verbose_name='Motivo de actualización')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_configuraciones_guardia_pasiva', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='liquidacion.configuracionguardiapasiva', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Historial de configuración de Guardia Pasiva',
                'verbose_name_plural': 'Historial de configuración de Guardia Pasiva',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
