# Generated by Django 5.2.12 on 2026-05-23 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0033_dop_grupo_periferico_y_contexto_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSesionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('ABIERTA', 'Abierta - Médicos pueden registrar'), ('REVISION', 'En Revisión - Cierre preliminar'), ('CERRADA', 'Cerrada - Solo Admin puede cargar faltantes'), ('FACTURADA', 'Facturada - Montos calculados y definitivos'), ('PAGADA', 'Pagada - Profesionales cobraron')], max_length=10, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('ABIERTA', 'Abierta - Médicos pueden registrar'), ('REVISION', 'En Revisión - Cierre preliminar'), ('CERRADA', 'Cerrada - Solo Admin puede cargar faltantes'), ('FACTURADA', 'Facturada - Montos calculados y definitivos'), ('PAGADA', 'Pagada - Profesionales cobraron')], max_length=10, verbose_name='Estado nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('origen', models.CharField(choices=[('WEB', 'Portal Web'), ('ADMIN', 'Django Admin')], default='WEB', max_length=10, verbose_name='Origen')),
                ('observacion_sistema', models.TextField(blank=True, verbose_name='Observación sistema')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_transiciones', to='liquidacion.sesioncontable', verbose_name='Sesión Contable')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_sesiones_contables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Sesión Contable',
                'verbose_name_plural': 'Historiales de Sesión Contable',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['sesion_contable', '-fecha'], name='liquidacion_sesion__de0841_idx'), models.Index(fields=['origen', '-fecha'], name='liquidacion_origen_8febd1_idx')],
            },
        ),
    ]
