# Generated by Django 5.2.12 on 2026-06-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0034_historialsesioncontable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRevisionHorarioRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('horario_solicitado', models.CharField(choices=[('INTRA', 'Intra Residencia (50%)'), ('EXTRA', 'Extra Residencia (100%)'), ('NA', 'No Aplica (Staff)')], max_length=6, verbose_name='Horario solicitado')),
                ('fecha_hora_real_declarada', models.DateTimeField(verbose_name='Fecha/Hora real declarada')),
                ('motivo_solicitud', models.TextField(verbose_name='Motivo de solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_revision_horario', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revision_horario_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitud de revisión de horario',
                'verbose_name_plural': 'Solicitudes de revisión de horario',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', '-fecha_solicitud'], name='liquidacion_estado_4dec2a_idx'), models.Index(fields=['registro', 'estado'], name='liquidacion_registr_b7a72f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('registro',), name='uniq_revision_horario_pendiente_por_registro')],
            },
        ),
    ]
