# Generated by Django 5.2.12 on 2026-06-11 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0035_solicitudrevisionhorarioregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revision'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='observacion_revision',
            field=models.TextField(blank=True, default='', verbose_name='Observacion de revision'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revision_horario_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
