# Generated by Django 5.2.12 on 2026-06-12 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0036_solicitudrevisionhorarioregistro_campos_revision_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='aplicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revision_horario_aplicadas', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aplicacion'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='horario_anterior',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Horario anterior'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='horario_aplicado',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Horario aplicado'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='monto_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto anterior'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='monto_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto aplicado'),
        ),
        migrations.AddField(
            model_name='solicitudrevisionhorarioregistro',
            name='observacion_aplicacion',
            field=models.TextField(blank=True, default='', verbose_name='Observacion de aplicacion'),
        ),
    ]
