# Generated by Django 5.2.12 on 2026-06-16 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0037_solicitudrevisionhorarioregistro_campos_aplicacion_b2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDescuentoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_medico_residente', models.BooleanField(default=False)),
                ('aplica_jefe_residentes', models.BooleanField(default=False)),
                ('aplica_instructor_residentes', models.BooleanField(default=False)),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_descuento_residencia_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_descuento_residencia_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_descuento_residencia', to='liquidacion.estudios', verbose_name='Estudio')),
                ('grupo_tarifario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_descuento_residencia', to='liquidacion.grupotarifario', verbose_name='Grupo tarifario')),
            ],
            options={
                'verbose_name': 'Regla de descuento residencia',
                'verbose_name_plural': 'Reglas de descuento residencia',
                'ordering': ['-vigencia_desde', '-id'],
                'indexes': [models.Index(fields=['estudio', 'activo', 'vigencia_desde'], name='liquidacion_estudio_4de946_idx'), models.Index(fields=['grupo_tarifario', 'activo', 'vigencia_desde'], name='liquidacion_grupo_t_ca0b27_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('estudio__isnull', False), ('grupo_tarifario__isnull', True)), models.Q(('estudio__isnull', True), ('grupo_tarifario__isnull', False)), _connector='OR'), name='ck_regla_desc_residencia_entidad_exclusiva'), models.UniqueConstraint(condition=models.Q(('estudio__isnull', False)), fields=('estudio', 'vigencia_desde', 'activo'), name='uq_regla_desc_residencia_estudio_vigencia_activo'), models.UniqueConstraint(condition=models.Q(('grupo_tarifario__isnull', False)), fields=('grupo_tarifario', 'vigencia_desde', 'activo'), name='uq_regla_desc_residencia_grupo_vigencia_activo')],
            },
        ),
    ]
