# Generated by Django 5.2.12 on 2026-06-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0038_regladescuentoresidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRecalculoSolicitudRevisionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recalculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recalculo')),
                ('horario_usado', models.CharField(max_length=6, verbose_name='Horario usado')),
                ('monto_registro_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto registro anterior')),
                ('monto_aplicado_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto aplicado anterior')),
                ('monto_recalculado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto recalculado')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observacion')),
                ('motivo_sistema', models.TextField(blank=True, default='', verbose_name='Motivo sistema')),
                ('recalculado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalculos_revision_horario_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Recalculado por')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_recalculos_revision_horario', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_recalculos', to='liquidacion.solicitudrevisionhorarioregistro', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de recalculo de solicitud de revision',
                'verbose_name_plural': 'Historiales de recalculo de solicitudes de revision',
                'ordering': ['-fecha_recalculo'],
                'indexes': [models.Index(fields=['solicitud', '-fecha_recalculo'], name='liquidacion_solicit_443dae_idx'), models.Index(fields=['registro', '-fecha_recalculo'], name='liquidacion_registr_6d4eff_idx')],
            },
        ),
    ]
