# Generated by Django 5.2.12 on 2026-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0039_historial_recalculo_revision_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='liquidar_como_extra_residencia',
            field=models.BooleanField(default=False, help_text='Usar cuando la práctica corresponde a una lista asistencial fuera de la actividad docente habitual. El registro se liquidará como Extra Residencia.', verbose_name='Actividad asistencial fuera de rol docente / liquidar como Extra Residencia'),
        ),
    ]
