# Generated by Django 5.2.12 on 2026-06-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0040_liquidar_como_extra_residencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionLiquidacionRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Version')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PREPARADO', 'Preparado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('destinatarios_json', models.JSONField(blank=True, default=list, verbose_name='Destinatarios')),
                ('cc_json', models.JSONField(blank=True, default=list, verbose_name='CC')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo')),
                ('resumen_json', models.JSONField(verbose_name='Resumen snapshot')),
                ('snapshot_hash', models.CharField(max_length=64, verbose_name='Hash snapshot')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_rrhh_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_rrhh_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_rrhh', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Preparacion liquidacion RRHH',
                'verbose_name_plural': 'Preparaciones liquidacion RRHH',
                'ordering': ['-sesion_contable__año', '-sesion_contable__mes', '-version'],
                'indexes': [models.Index(fields=['sesion_contable', '-version'], name='liquidacion_sesion__7b84f8_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='liquidacion_estado_002712_idx')],
                'unique_together': {('sesion_contable', 'version')},
            },
        ),
    ]
