# Generated by Django 5.2.12 on 2026-06-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0041_preparacion_liquidacion_rrhh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAuditoriaEcoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('VALIDADO', 'Validado contra PACS'), ('REQUIERE_CORRECCION', 'Requiere correccion'), ('DESCARTADO', 'Descartado / no corresponde')], max_length=24, verbose_name='Estado')),
                ('motivos_json', models.JSONField(blank=True, default=list, verbose_name='Motivos detectados')),
                ('observacion', models.TextField(verbose_name='Observacion')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha revision')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria_eco', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria_eco_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria_eco', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Revision auditoria ECO',
                'verbose_name_plural': 'Revisiones auditoria ECO',
                'ordering': ['-fecha_revision'],
                'indexes': [models.Index(fields=['sesion_contable', '-fecha_revision'], name='liquidacion_sesion__022fdb_idx'), models.Index(fields=['registro', '-fecha_revision'], name='liquidacion_registr_316925_idx'), models.Index(fields=['estado', '-fecha_revision'], name='liquidacion_estado_5c4e95_idx')],
            },
        ),
    ]
