# Generated by Django 5.2.12 on 2026-06-30 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0042_revision_auditoria_eco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionPacsRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto anterior')),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto nuevo')),
                ('observacion', models.TextField(verbose_name='Observacion')),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha correccion')),
                ('corregido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_pacs_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Corregido por')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_pacs', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('revision_auditoria_eco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_pacs', to='liquidacion.revisionauditoriaecoregistro', verbose_name='Revision auditoria ECO')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_pacs', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Correccion PACS de registro',
                'verbose_name_plural': 'Correcciones PACS de registros',
                'ordering': ['-fecha_correccion'],
                'indexes': [models.Index(fields=['sesion_contable', '-fecha_correccion'], name='liquidacion_sesion__13d259_idx'), models.Index(fields=['registro', '-fecha_correccion'], name='liquidacion_registr_18f506_idx')],
            },
        ),
    ]
