# Generated by Django 5.2.12 on 2026-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0043_correccion_pacs_auditoria_eco'),
    ]

    operations = [
        migrations.AddField(
            model_name='correccionpacsregistro',
            name='horario_anterior',
            field=models.CharField(blank=True, choices=[('INTRA', 'Intra Residencia (50%)'), ('EXTRA', 'Extra Residencia (100%)'), ('NA', 'No Aplica (Staff)')], max_length=6, null=True, verbose_name='Horario anterior'),
        ),
        migrations.AddField(
            model_name='correccionpacsregistro',
            name='horario_nuevo',
            field=models.CharField(blank=True, choices=[('INTRA', 'Intra Residencia (50%)'), ('EXTRA', 'Extra Residencia (100%)'), ('NA', 'No Aplica (Staff)')], max_length=6, null=True, verbose_name='Horario nuevo'),
        ),
        migrations.AddField(
            model_name='correccionpacsregistro',
            name='tipo_correccion',
            field=models.CharField(choices=[('MONTO_MANUAL', 'Monto manual'), ('HORARIO_RECALCULADO', 'Horario corregido y recalculado')], default='MONTO_MANUAL', max_length=24, verbose_name='Tipo de correccion'),
        ),
    ]
