# Generated by Django 5.2.12 on 2026-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0044_correccion_pacs_horario_recalculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correccionpacsregistro',
            name='hora_pacs',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora vista en PACS'),
        ),
    ]
