# Generated by Django 5.2.12 on 2026-07-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0045_correccion_pacs_hora_pacs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRecalculoTarifaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto anterior')),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto nuevo')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diferencia')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha_recalculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha recalculo')),
                ('recalculado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalculos_tarifa_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Recalculado por')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_recalculos_tarifa', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_recalculos_tarifa', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Historial de recalculo por tarifa',
                'verbose_name_plural': 'Historiales de recalculo por tarifa',
                'ordering': ['-fecha_recalculo'],
                'indexes': [models.Index(fields=['sesion_contable', '-fecha_recalculo'], name='liquidacion_sesion__b2bb5d_idx'), models.Index(fields=['registro', '-fecha_recalculo'], name='liquidacion_registr_af1b5d_idx'), models.Index(fields=['fecha_desde', 'fecha_hasta'], name='liquidacion_fecha_d_611e2a_idx')],
            },
        ),
    ]
