# Generated by Django 5.2.12 on 2026-07-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0046_historial_recalculo_tarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionguardiapasiva',
            name='vigente_hasta',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual rige este valor. Vacio significa vigencia abierta.', null=True, verbose_name='Vigente hasta'),
        ),
    ]
