# Generated by Django 5.2.12 on 2026-08-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0007_eges_campos_auditoria_pacs'),
        ('liquidacion', '0048_historial_recalculo_tarifa_guardia_pasiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCruceEgesRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('VALIDADO', 'Validado contra EGES'), ('REQUIERE_CORRECCION', 'Requiere correccion'), ('DESCARTADO', 'Descartado / no corresponde')], max_length=24, verbose_name='Estado')),
                ('motivos_json', models.JSONField(blank=True, default=list, verbose_name='Motivos detectados')),
                ('snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='Snapshot cruce EGES')),
                ('observacion', models.TextField(verbose_name='Observacion')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha revision')),
                ('batch_eges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_liquidacion', to='eges_import.importbatch', verbose_name='Batch EGES')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_cruce_eges', to='liquidacion.registroestudiospormedico', verbose_name='Registro')),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_cruce_eges_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_cruce_eges', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Revision cruce EGES',
                'verbose_name_plural': 'Revisiones cruce EGES',
                'ordering': ['-fecha_revision'],
                'indexes': [models.Index(fields=['sesion_contable', '-fecha_revision'], name='liquidacion_sesion__8d7d1f_idx'), models.Index(fields=['registro', 'batch_eges', '-fecha_revision'], name='liquidacion_registr_720a92_idx'), models.Index(fields=['estado', '-fecha_revision'], name='liquidacion_estado_4a26ed_idx')],
            },
        ),
    ]
