# Generated by Django 5.2.12 on 2026-08-03 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0007_eges_campos_auditoria_pacs'),
        ('liquidacion', '0049_revision_cruce_eges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEgesSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Version')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_ok', models.PositiveIntegerField(default=0)),
                ('total_advertencias', models.PositiveIntegerField(default=0)),
                ('total_manuales', models.PositiveIntegerField(default=0)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('batch_eges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_liquidacion', to='eges_import.importbatch', verbose_name='Batch EGES')),
                ('procesado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_eges_procesados', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('sesion_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_eges', to='liquidacion.sesioncontable', verbose_name='Sesion contable')),
            ],
            options={
                'verbose_name': 'Control EGES de sesion',
                'verbose_name_plural': 'Controles EGES de sesiones',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoControlEgesRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OK', 'Coincidencia'), ('ADVERTENCIA', 'Advertencia'), ('MANUAL', 'Revision manual')], max_length=16)),
                ('motivos_json', models.JSONField(blank=True, default=list)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='liquidacion.controlegessesion')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_control_eges', to='liquidacion.registroestudiospormedico')),
            ],
            options={
                'verbose_name': 'Resultado de control EGES',
                'verbose_name_plural': 'Resultados de control EGES',
            },
        ),
        migrations.AddIndex(
            model_name='controlegessesion',
            index=models.Index(fields=['sesion_contable', '-fecha_procesamiento'], name='liquidacion_sesion__16b407_idx'),
        ),
        migrations.AddIndex(
            model_name='controlegessesion',
            index=models.Index(fields=['batch_eges', '-fecha_procesamiento'], name='liquidacion_batch_e_a25fe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='controlegessesion',
            constraint=models.UniqueConstraint(fields=('sesion_contable', 'version'), name='liq_control_eges_sesion_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='resultadocontrolegesregistro',
            index=models.Index(fields=['control', 'estado'], name='liquidacion_control_93c43e_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadocontrolegesregistro',
            index=models.Index(fields=['registro'], name='liquidacion_registr_aa2bf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadocontrolegesregistro',
            constraint=models.UniqueConstraint(fields=('control', 'registro'), name='liq_resultado_control_eges_registro_uniq'),
        ),
    ]
