# Generated by Django 5.2.12 on 2026-08-04 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0050_control_eges_sesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='anulado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroestudiospormedico',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='registroestudiospormedico',
            index=models.Index(fields=['sesion_contable', 'anulado'], name='liquidacion_sesion__ec695a_idx'),
        ),
    ]
