# Generated by Django 5.2.12 on 2026-09-05 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0051_anulacion_registro_estudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaContractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('semana', models.JSONField()),
                ('observacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_contractuales_cerradas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_contractuales_creadas', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_contractuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['profesional_id', '-vigencia_desde'],
                'permissions': [('gestionar_jornadas_contractuales', 'Puede gestionar jornadas contractuales')],
                'constraints': [models.UniqueConstraint(fields=('profesional', 'vigencia_desde'), name='jornada_profesional_desde_unica'), models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='jornada_vigencia_valida')],
            },
        ),
    ]
