# Generated by Django 5.2.12 on 2026-10-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0052_jornada_contractual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAuditoriaDopplerMMII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_estudio_id_origen', models.PositiveIntegerField()),
                ('version_regla', models.CharField(default='DOPPLER_MMII_V1', max_length=40)),
                ('datos_originales_json', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('CONFIRMADO', 'Diferencia confirmada'), ('DESCARTADO', 'Diferencia descartada'), ('REQUIERE_EVIDENCIA', 'Requiere evidencia')], default='PENDIENTE', max_length=24)),
                ('orden_medica_verificada', models.BooleanField(default=False)),
                ('eges_verificado', models.BooleanField(default=False)),
                ('visualmedical_verificado', models.BooleanField(default=False)),
                ('netterm_verificado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria_doppler_mmii', to='liquidacion.registroestudiospormedico')),
                ('registro_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_auditoria_doppler_mmii', to='liquidacion.registroestudio')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria_doppler_mmii_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revision auditoria Doppler MMII',
                'verbose_name_plural': 'Revisiones auditoria Doppler MMII',
                'ordering': ['-fecha_deteccion'],
                'indexes': [models.Index(fields=['registro', 'estado'], name='liquidacion_registr_ea05c0_idx'), models.Index(fields=['estado', '-fecha_deteccion'], name='liquidacion_estado_5d577b_idx')],
                'constraints': [models.UniqueConstraint(fields=('registro', 'registro_estudio_id_origen', 'version_regla'), name='liq_audit_doppler_linea_regla_uniq')],
            },
        ),
    ]
