# Generated by Django 5.2.12 on 2026-10-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0053_revisionauditoriadopplermmii'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRevisionAuditoriaDopplerMMII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=24)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('CONFIRMADO', 'Diferencia confirmada'), ('DESCARTADO', 'Diferencia descartada'), ('REQUIERE_EVIDENCIA', 'Requiere evidencia')], max_length=24)),
                ('orden_medica_verificada', models.BooleanField(default=False)),
                ('eges_verificado', models.BooleanField(default=False)),
                ('visualmedical_verificado', models.BooleanField(default=False)),
                ('netterm_verificado', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_auditoria_doppler_mmii_realizado', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='liquidacion.revisionauditoriadopplermmii')),
            ],
            options={
                'verbose_name': 'Historial de revision auditoria Doppler MMII',
                'verbose_name_plural': 'Historiales de revision auditoria Doppler MMII',
                'ordering': ['-fecha_revision'],
                'indexes': [models.Index(fields=['revision', '-fecha_revision'], name='liquidacion_revisio_5643c2_idx')],
            },
        ),
    ]
