# Generated by Django 5.2.12 on 2026-10-03 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0054_historialrevisionauditoriadopplermmii'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionauditoriadopplermmii',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_auditoria_doppler_mmii_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
