# Generated by Django 5.2.12 on 2026-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0055_revisionauditoriadopplermmii_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialrevisionauditoriadopplermmii',
            name='estimacion_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='revisionauditoriadopplermmii',
            name='estimacion_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
