# Generated by Django 5.2.12 on 2026-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0056_historialrevisionauditoriadopplermmii_estimacion_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestudio',
            name='cantidad_liquidable',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad aplicada por una corrección auditada; vacío conserva la cantidad declarada.', null=True, verbose_name='Cantidad liquidable corregida'),
        ),
    ]
