# Generated by Django 5.2.12 on 2026-10-08 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0057_registroestudio_cantidad_liquidable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAjusteCantidadDopplerMMII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_estudio_id_origen', models.PositiveIntegerField()),
                ('lote_id', models.UUIDField(db_index=True)),
                ('accion', models.CharField(choices=[('APLICAR', 'Aplicar regla de cantidad'), ('REVERTIR', 'Revertir regla de cantidad')], max_length=12)),
                ('version_regla', models.CharField(max_length=40)),
                ('cantidad_declarada', models.PositiveSmallIntegerField()),
                ('cantidad_liquidable_anterior', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cantidad_liquidable_nueva', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_registro_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_registro_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('evento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversiones', to='liquidacion.historialajustecantidaddopplermmii')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ajustes_cantidad_doppler_realizados', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ajustes_cantidad_doppler_mmii', to='liquidacion.registroestudiospormedico')),
                ('registro_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ajustes_cantidad_doppler_mmii', to='liquidacion.registroestudio')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ajustes_cantidad', to='liquidacion.revisionauditoriadopplermmii')),
            ],
            options={
                'verbose_name': 'Historial de ajuste de cantidad Doppler MMII',
                'verbose_name_plural': 'Historiales de ajustes de cantidad Doppler MMII',
                'ordering': ['-fecha_evento', '-pk'],
                'indexes': [models.Index(fields=['registro', '-fecha_evento'], name='liquidacion_registr_2bbc6f_idx'), models.Index(fields=['registro_estudio_id_origen', '-fecha_evento'], name='liquidacion_registr_d4c6d2_idx'), models.Index(fields=['lote_id', 'accion'], name='liquidacion_lote_id_8803fc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accion', 'REVERTIR')), fields=('evento_origen',), name='liq_doppler_ajuste_reversion_unica')],
            },
        ),
    ]
