# Generated by Django 4.2.25 on 2025-12-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField()),
                ('fijada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Personal',
                'verbose_name_plural': 'Notas Personales',
                'ordering': ['-fijada', '-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CITA', 'Cita'), ('REUNION', 'Reunión'), ('LLAMADA', 'Llamada'), ('RECORDATORIO', 'Recordatorio'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('es_importante', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Agenda',
                'verbose_name_plural': 'Items de Agenda',
                'ordering': ['fecha', 'hora_inicio', 'titulo'],
            },
        ),
    ]
