# Generated by Django 5.2.12 on 2026-03-28 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Área / Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Área de Servicio',
                'verbose_name_plural': 'Áreas de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código de Barras')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('descartable', 'Descartable'), ('medicamento', 'Medicamento'), ('material_procedimiento', 'Material de Procedimiento'), ('material_limpieza', 'Material de Limpieza'), ('instrumental', 'Instrumental'), ('equipo_menor', 'Equipo Menor'), ('otro', 'Otro')], default='descartable', max_length=30, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('frasco', 'Frasco'), ('ampolla', 'Ampolla'), ('bolsa', 'Bolsa'), ('rollo', 'Rollo'), ('par', 'Par'), ('litro', 'Litro'), ('ml', 'ml'), ('gramo', 'Gramo'), ('otro', 'Otro')], default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo de alerta')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen (producto)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('numero_lote', models.CharField(blank=True, max_length=100, verbose_name='Número de lote')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control_stock.areaservicio', verbose_name='Área')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control_stock.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StockPorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en stock')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='control_stock.areaservicio', verbose_name='Área')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_area', to='control_stock.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock por Área',
                'verbose_name_plural': 'Stock por Área',
                'ordering': ['producto__nombre'],
                'unique_together': {('producto', 'area')},
            },
        ),
    ]
