# Generated by Django 5.2.12 on 2026-03-28 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='anulacion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_anulacion', to='control_stock.movimientostock', verbose_name='Anulación de'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
    ]
