# Generated by Django 5.2.12 on 2026-03-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0002_movimientostock_anulacion_de_movimientostock_anulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada / Reposición'), ('salida', 'Salida'), ('uso', 'Uso en procedimiento'), ('descarte', 'Descarte'), ('ajuste', 'Ajuste de inventario')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='LoteEnArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en este lote')),
                ('activo', models.BooleanField(default=True, help_text='False cuando el lote fue descartado o agotado.', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='control_stock.stockporarea', verbose_name='Stock por área')),
            ],
            options={
                'verbose_name': 'Lote en Área',
                'verbose_name_plural': 'Lotes en Área',
                'ordering': ['fecha_vencimiento', 'creado_en'],
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='control_stock.loteenarea', verbose_name='Lote afectado'),
        ),
        migrations.AddIndex(
            model_name='loteenarea',
            index=models.Index(fields=['stock', 'activo', 'fecha_vencimiento'], name='control_sto_stock_i_a328a8_idx'),
        ),
    ]
