# Generated by Django 5.2.12 on 2026-03-28 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0003_lote_en_area_y_nuevos_tipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loteenarea',
            name='reportado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loteenarea',
            name='reportado_para_descarte',
            field=models.BooleanField(default=False, help_text='Un usuario sin permisos lo marcó como vencido/a descartar.', verbose_name='Reportado para descarte'),
        ),
        migrations.AddField(
            model_name='loteenarea',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
    ]
