# Generated by Django 5.2.12 on 2026-08-22 15:48

import django.core.validators
import django.db.models.deletion
import portafolio.models
import portafolio.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('CONGRESO_JORNADA', 'Congreso o jornada'), ('ATENEO_PRESENTACION', 'Ateneo o presentación'), ('TRABAJO_CIENTIFICO', 'Trabajo científico, publicación o póster'), ('ACTIVIDAD_DOCENTE', 'Actividad docente'), ('ROTACION_EXTERNA', 'Rotación externa'), ('OTRA', 'Otra actividad curricular')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('enlace', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada para revisión'), ('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada')], db_index=True, default='BORRADOR', max_length=20)),
                ('observacion_docente', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(limit_choices_to={'rol': 'medico_residente'}, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_curriculares', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_curriculares_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad curricular',
                'verbose_name_plural': 'Actividades curriculares',
                'ordering': ['-fecha_inicio', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoActividadCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, storage=portafolio.storage.PrivatePortfolioStorage(), upload_to=portafolio.models.upload_evidencia_actividad, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx'])])),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('CONSTANCIA', 'Constancia'), ('PROGRAMA', 'Programa'), ('EVALUACION', 'Evaluación'), ('OTRO', 'Otro documento')], default='CERTIFICADO', max_length=20)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=150)),
                ('tamanio_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='portafolio.actividadcurricular')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_curriculares_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de actividad curricular',
                'verbose_name_plural': 'Documentos de actividades curriculares',
                'ordering': ['subido_en'],
            },
        ),
        migrations.AddIndex(
            model_name='actividadcurricular',
            index=models.Index(fields=['residente', 'estado', 'fecha_inicio'], name='port_act_res_estado_fecha_idx'),
        ),
    ]
