# Generated by Django 5.1.4 on 2025-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='dicoms/')),
                ('nombre_subido', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
