"""
Django settings for gestion_estudios project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import dj_database_url

# Importar configuración del sanatorio
from .config_sanatorio import CONFIG as SANATORIO_CONFIG

# Construya rutas dentro del proyecto de esta manera: BASE_DIR /'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuración de desarrollo de inicio rápido: no adecuada para producción
# Ver https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: ¡mantenga en secreto la clave secreta utilizada en la producción!
# Configuración sensible desde el archivo .env
SECRET_KEY = config('SECRET_KEY')

# ADVERTENCIA DE SEGURIDAD: ¡no ejecute con la depuración activada en producción!
DEBUG = config('DEBUG', default='False').lower() in ['true', '1', 't']

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Cloudinary (para almacenamiento de archivos)
    'cloudinary_storage',
    'cloudinary',
    
    # CKEditor 5 para texto enriquecido
    'django_ckeditor_5',
    
    # Apps principales del proyecto
    'accounts.apps.AccountsConfig',
    'control_guardias.apps.ControlGuardiasConfig',
    'liquidacion.apps.LiquidacionConfig',
    'gestion_eventos.apps.GestionEventosConfig',
    'dictado_informes.apps.DictadoInformesConfig',
    'equipos.apps.EquiposConfig',
    'agenda.apps.AgendaConfig',
    'protocolos.apps.ProtocolosConfig',
    'clases_residentes.apps.ClasesResidentesConfig',
    'eges_import.apps.EgesImportConfig',
    'preinformes.apps.PreinformesConfig',
    'consultorios.apps.ConsultoriosConfig',
    
    # Tailwind CSS
    'tailwind',
    'theme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Debe ir después de SecurityMiddleware
    'gestion_estudios.middleware.NoCacheMiddleware',  # Prevenir cacheo agresivo
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Debe estar antes de ProfileRequiredMiddleware
    'accounts.middleware.ProfileRequiredMiddleware',  # Verificar perfil completo
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_estudios.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dictado_informes.context_processors.terminos_activos',
                'gestion_estudios.context_processors.sanatorio_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_estudios.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
    )
}


# Validación de contraseña
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_REDIRECT_URL = 'home'  # Redirigir al home después de iniciar sesión
LOGOUT_REDIRECT_URL = 'login'  # Redirigir al login después de cerrar sesión
LOGIN_URL = 'login'  # Página de login predeterminada


# Internacionalización
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

# Usar zona horaria del sanatorio activo
TIME_ZONE = SANATORIO_CONFIG['ZONA_HORARIA']

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme/static'),  # Tailwind CSS compilado por django-tailwind
    os.path.join(BASE_DIR, 'static'),  # Otros archivos estáticos (imágenes, etc.)
]

# Almacenamiento para Heroku con WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Configuración de WhiteNoise
WHITENOISE_AUTOREFRESH = True if DEBUG else False
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MAX_AGE = 0 if DEBUG else 31536000  # 1 año en producción

# Archivos subidos por usuarios (imágenes, documentos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Paleta de colores personalizada para CKEditor 5
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# Configuración de CKEditor 5 (optimizada para copiar/pegar desde Word)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 
            'bold', 'italic', 'underline', '|',
            'bulletedList', 'numberedList', '|',
            'outdent', 'indent', '|',
            'fontSize', 'fontColor', '|',
            'subscript', 'superscript', '|',
            'undo', 'redo', '|',
            'removeFormat', '|',
            'sourceEditing'  # Permite ver/editar HTML directamente
        ],
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5' },
                { 'model': 'heading6', 'view': 'h6', 'title': 'Heading 6' }
            ]
        },
        'fontSize': {
            'options': [
                '12', '14', '16', '18', '20', '24'
            ]
        },
        'fontColor': {
            'colors': [
                { 'color': '#000000', 'label': 'Negro' },
                { 'color': '#d32f2f', 'label': 'Rojo (Hallazgos importantes)' },
                { 'color': '#1976d2', 'label': 'Azul (Conclusiones)' },
                { 'color': '#388e3c', 'label': 'Verde' },
                { 'color': '#f57c00', 'label': 'Naranja' }
            ]
        },
        # Preservar formatos al pegar desde Word (saltos de línea, negritas, listas, etc.)
        'htmlSupport': {
            'allow': [
                {
                    'name': r'^(p|br|span|strong|b|em|i|u|s|sub|sup|ol|ul|li|h[1-6]|div)$',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                }
            ]
        }
    }
}

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Tipo de campo de clave principal predeterminado
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURACIÓN DE TAILWIND CSS
# =============================================================================

# Nombre de la app que contendrá los estilos de Tailwind
TAILWIND_APP_NAME = 'theme'

# Configuración solo para desarrollo - hot reload
if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

# Configuración del navegador para desarrollo (opcional)
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"  # Ruta al binario de npm

# =============================================================================
# CONFIGURACIÓN DE EMAIL - Paso a Paso
# =============================================================================
# 
# BACKEND: El "motor" que envía emails
# - console → muestra en terminal (para practicar) ✅
# - smtp → envía emails reales (para producción)
# - filebased → guarda en archivos (para testing)

EMAIL_BACKEND = config(
    'EMAIL_BACKEND', 
    default='django.core.mail.backends.console.EmailBackend'  # ← Console por defecto para practicar
)

# Configuración SMTP (solo se usa si EMAIL_BACKEND = smtp)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="noreply@example.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@example.com")

# -----------------------------------------------------------------------------
# LOGGING: Forzar que los errores del middleware personalizado aparezcan siempre.
# Heroku captura stdout/stderr, así que añadimos handlers de consola.
# -----------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'gestion_estudios.middleware': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ============================================================================
# CLOUDINARY CONFIGURATION
# ============================================================================
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default='')
}

# Solo usar Cloudinary si está configurado
if all([CLOUDINARY_STORAGE['CLOUD_NAME'], CLOUDINARY_STORAGE['API_KEY'], CLOUDINARY_STORAGE['API_SECRET']]):
    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
        api_key=CLOUDINARY_STORAGE['API_KEY'],
        api_secret=CLOUDINARY_STORAGE['API_SECRET'],
        secure=True
    )
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    print("✓ Cloudinary configurado correctamente")
else:
    print("⚠ Cloudinary NO configurado - usando almacenamiento local")