"""
Django settings for gestion_estudios project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import dj_database_url

# Importar configuración del sanatorio
from .config_sanatorio import CONFIG as SANATORIO_CONFIG

# Construya rutas dentro del proyecto de esta manera: BASE_DIR /'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuración de desarrollo de inicio rápido: no adecuada para producción
# Ver https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: ¡mantenga en secreto la clave secreta utilizada en la producción!
# Configuración sensible desde el archivo .env
SECRET_KEY = config('SECRET_KEY')

# ADVERTENCIA DE SEGURIDAD: ¡no ejecute con la depuración activada en producción!
DEBUG = config('DEBUG', default='False').lower() in ['true', '1', 't']

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Administradores del sistema (reciben alertas de errores)
ADMINS = [
    ('Enso Cejas', 'ensofermincejas@gmail.com'),
]
MANAGERS = ADMINS

# Email predeterminado para notificaciones de pedidos (destinatario fallback)
PEDIDOS_EMAIL_DEFAULT = 'ecejas@sanatoriocolegiales.com.ar'

# Email remitente específico para notificaciones de pedidos (puede ser diferente al DEFAULT_FROM_EMAIL)
PEDIDOS_FROM_EMAIL = config('PEDIDOS_FROM_EMAIL', default=None)  # Si no se define, usa DEFAULT_FROM_EMAIL

# URL base del sitio (para generar enlaces en emails)
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Configuración de validación de pedidos
# Score mínimo de confianza para aceptar un email como pedido válido (0-100)
PEDIDOS_SCORE_MINIMO = config('PEDIDOS_SCORE_MINIMO', default=50, cast=int)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Cloudinary (para almacenamiento de archivos)
    'cloudinary_storage',
    'cloudinary',
    
    # CKEditor 5 para texto enriquecido
    'django_ckeditor_5',
    
    # Apps principales del proyecto
    'accounts.apps.AccountsConfig',
    'control_guardias.apps.ControlGuardiasConfig',
    'liquidacion.apps.LiquidacionConfig',
    'gestion_eventos.apps.GestionEventosConfig',
    'dictado_informes.apps.DictadoInformesConfig',
    'equipos.apps.EquiposConfig',
    'agenda.apps.AgendaConfig',
    'protocolos.apps.ProtocolosConfig',
    'clases_residentes.apps.ClasesResidentesConfig',
    'eges_import.apps.EgesImportConfig',
    'preinformes.apps.PreinformesConfig',
    'consultorios.apps.ConsultoriosConfig',
    'pedidos_estudios.apps.PedidosEstudiosConfig',  # Sistema de pedidos por email
    'ahorro_vivienda.apps.AhorroViviendaConfig',  # Tracker ahorro primera vivienda
    'control_stock.apps.ControlStockConfig',  # Control de stock con escáner + IA
    
    # Tailwind CSS
    'tailwind',
    'theme',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Debe ir después de SecurityMiddleware
    'gestion_estudios.middleware.NoCacheMiddleware',  # Prevenir cacheo agresivo
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Debe estar antes de ProfileRequiredMiddleware
    'accounts.middleware.ProfileRequiredMiddleware',  # Verificar perfil completo
    'accounts.middleware.SessionTimeoutMiddleware',  # Cerrar sesión por inactividad
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_estudios.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dictado_informes.context_processors.terminos_activos',
                'gestion_estudios.context_processors.sanatorio_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_estudios.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
    )
}


# Validación de contraseña
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
            'max_similarity': 0.7,  # Rechaza passwords similares a datos del usuario
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_REDIRECT_URL = 'home'  # Redirigir al home después de iniciar sesión
LOGOUT_REDIRECT_URL = 'login'  # Redirigir al login después de cerrar sesión
LOGIN_URL = 'login'  # Página de login predeterminada


# Internacionalización
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

# Usar zona horaria del sanatorio activo
TIME_ZONE = SANATORIO_CONFIG['ZONA_HORARIA']

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme/static'),  # Tailwind CSS compilado por django-tailwind
    os.path.join(BASE_DIR, 'static'),  # Otros archivos estáticos (imágenes, etc.)
]

# Almacenamiento para Heroku con WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Usar CompressedManifestStaticFilesStorage sin strict mode
        # para evitar errores de encoding en archivos CSS con caracteres especiales
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        "OPTIONS": {
            "manifest_strict": False,
        },
    },
}

# Deshabilitar post-processing de WhiteNoise para evitar errores de encoding
WHITENOISE_AUTOREFRESH = True
WHITENOISE_USE_FINDERS = True

# Configuración de WhiteNoise
WHITENOISE_AUTOREFRESH = True if DEBUG else False
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MAX_AGE = 0 if DEBUG else 31536000  # 1 año en producción

# Archivos subidos por usuarios (imágenes, documentos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Paleta de colores personalizada para CKEditor 5
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# Configuración de CKEditor 5 (optimizada para copiar/pegar desde Word)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 
            'bold', 'italic', 'underline', '|',
            'bulletedList', 'numberedList', '|',
            'outdent', 'indent', '|',
            'fontSize', 'fontColor', '|',
            'subscript', 'superscript', '|',
            'undo', 'redo', '|',
            'removeFormat', '|',
            'sourceEditing'  # Permite ver/editar HTML directamente
        ],
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5' },
                { 'model': 'heading6', 'view': 'h6', 'title': 'Heading 6' }
            ]
        },
        'fontSize': {
            'options': [
                '12', '14', '16', '18', '20', '24'
            ]
        },
        'fontColor': {
            'colors': [
                { 'color': '#000000', 'label': 'Negro' },
                { 'color': '#d32f2f', 'label': 'Rojo (Hallazgos importantes)' },
                { 'color': '#1976d2', 'label': 'Azul (Conclusiones)' },
                { 'color': '#388e3c', 'label': 'Verde' },
                { 'color': '#f57c00', 'label': 'Naranja' }
            ]
        },
        # Preservar formatos al pegar desde Word (saltos de línea, negritas, listas, etc.)
        'htmlSupport': {
            'allow': [
                {
                    'name': r'^(p|br|span|strong|b|em|i|u|s|sub|sup|ol|ul|li|h[1-6]|div)$',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                }
            ]
        }
    }
}

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Tipo de campo de clave principal predeterminado
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURACIÓN DE TAILWIND CSS
# =============================================================================

# Nombre de la app que contendrá los estilos de Tailwind
TAILWIND_APP_NAME = 'theme'

# Configuración solo para desarrollo - hot reload
if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

# Configuración del navegador para desarrollo (opcional)
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"  # Ruta al binario de npm

# =============================================================================
# CONFIGURACIÓN DE EMAIL - Paso a Paso
# =============================================================================
# 
# BACKEND: El "motor" que envía emails
# - console → muestra en terminal (para practicar) ✅
# - smtp → envía emails reales (para producción)
# - filebased → guarda en archivos (para testing)

EMAIL_BACKEND = config(
    'EMAIL_BACKEND', 
    default='django.core.mail.backends.console.EmailBackend'  # ← Console por defecto para practicar
)

# Configuración SMTP (solo se usa si EMAIL_BACKEND = smtp)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="noreply@example.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@example.com")

# -----------------------------------------------------------------------------
# LOGGING: Sistema mejorado con archivos y alertas
# -----------------------------------------------------------------------------
import os
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            'class': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            'class': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'general.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'file_pedidos': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'pedidos_estudios.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'include_html': True,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'gestion_estudios.middleware': {
            'handlers': ['console', 'file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'pedidos_estudios': {
            'handlers': ['console', 'file_pedidos', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'pedidos_estudios.services': {
            'handlers': ['console', 'file_pedidos', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ============================================================================
# CLOUDINARY CONFIGURATION
# ============================================================================
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default='')
}

# Solo usar Cloudinary si está configurado
if all([CLOUDINARY_STORAGE['CLOUD_NAME'], CLOUDINARY_STORAGE['API_KEY'], CLOUDINARY_STORAGE['API_SECRET']]):
    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
        api_key=CLOUDINARY_STORAGE['API_KEY'],
        api_secret=CLOUDINARY_STORAGE['API_SECRET'],
        secure=True
    )
    print("[OK] Cloudinary configurado correctamente")
else:
    print("[WARNING] Cloudinary NO configurado - usando almacenamiento local")

# URL de la plantilla base para ateneos (archivo PPTX en Cloudinary)
# Para actualizar: subir el nuevo archivo a Cloudinary y actualizar esta variable en el .env
PLANTILLA_ATENEO_URL = config('PLANTILLA_ATENEO_URL', default='')

# Configuración de AWS S3 / MinIO
from decouple import config
AWS_ACCESS_KEY_ID = config('STACKHERO_MINIO_ROOT_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = config('STACKHERO_MINIO_ROOT_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = 'gestion-servicio'  # El nombre exacto de tu bucket
AWS_S3_ENDPOINT_URL = f"https://{config('STACKHERO_MINIO_HOST')}"
AWS_S3_REGION_NAME = 'us-east-1'  # MinIO suele usar esto por defecto
AWS_S3_USE_SSL = True
AWS_S3_ADDRESSING_STYLE = "path"

# STORAGES: Sistema múltiple de almacenamiento (Django 4.2+)
# S3/MinIO para documentos (PPT, PDF) y Cloudinary para videos
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# =============================================================================
# 🔒 CONFIGURACIÓN DE SEGURIDAD
# =============================================================================

# Headers de seguridad HTTP
# --------------------------

# Prevenir clickjacking (iframe embedding)
X_FRAME_OPTIONS = 'DENY'

# Prevenir MIME-type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Activar XSS filter del navegador
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy
SECURE_REFERRER_POLICY = 'same-origin'

# Configuración de Cookies Seguras
# ---------------------------------

# Cookies HTTPOnly (prevenir acceso desde JavaScript - Anti-XSS)
# Tiempo de inactividad antes de cerrar sesión automáticamente (segundos)
# Valor por defecto: 30 minutos. Ajustar con SESSION_INACTIVITY_TIMEOUT en .env
SESSION_INACTIVITY_TIMEOUT = int(config('SESSION_INACTIVITY_TIMEOUT', default=30 * 60))

SESSION_COOKIE_HTTPONLY = True

# CSRF Cookie: False para permitir peticiones AJAX
# Nota: El token CSRF por sí solo no compromete la sesión, 
# y es necesario para aplicaciones modernas con fetch/AJAX
CSRF_COOKIE_HTTPONLY = False

# SameSite cookies (prevenir CSRF)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Configuración HTTPS (solo en producción)
# ----------------------------------------
if not DEBUG:
    # Redirigir todo el tráfico a HTTPS
    SECURE_SSL_REDIRECT = True
    
    # HTTP Strict Transport Security (HSTS) - 1 año
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies solo por HTTPS en producción
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# =============================================================================
# CONFIGURACIÓN LOCAL (no se sube a Git)
# =============================================================================
# Importar configuración local si existe
try:
    from .settings_local import *
    print("[OK] settings_local.py importado correctamente")
except ImportError:
    # Solo mostrar warning en desarrollo local (no en Heroku)
    if not os.getenv('DYNO'):  # DYNO existe solo en Heroku
        print("[WARNING] settings_local.py no encontrado - usando solo configuración base")