# Generated by Django 5.1.4 on 2024-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, choices=[('jefe', 'Jefe de servicio'), ('jefe tecnico', 'Jefe técnico'), ('jefe administrativo', 'Jefe administrativo'), ('médico', 'Médico'), ('médico residente', 'Médico residente'), ('técnico radiólogo', 'Técnico radiólogo'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
