# Generated by Django 4.2.25 on 2025-12-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_perfil_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se completó el perfil por primera vez', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfil_completo',
            field=models.BooleanField(default=False, help_text='Indica si el usuario completó su perfil post-registro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(blank=True, choices=[('medico_staff', 'Médico de Staff'), ('medico_residente', 'Médico Residente'), ('jefe_servicio', 'Jefe de Servicio'), ('tecnico', 'Técnico Radiólogo'), ('administrativo', 'Administrativo'), ('enfermeria', 'Enfermería'), ('otro', 'Otro')], help_text='Rol principal del usuario en el servicio', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo o especialización específica (opcional)', max_length=50, null=True),
        ),
    ]
