# Generated by Django 4.2.25 on 2025-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_fecha_perfil_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anio_residencia',
            field=models.CharField(blank=True, help_text='Año de residencia calculado automáticamente (R1, R2, R3, R4, R5)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_ingreso_residencia',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la residencia (para cálculo automático de año)', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(blank=True, choices=[('medico_staff', 'Médico de Staff'), ('medico_residente', 'Médico Residente'), ('jefe_residentes', 'Jefe de Residentes'), ('instructor_residentes', 'Instructor de Residentes'), ('jefe_servicio', 'Jefe de Servicio'), ('tecnico', 'Técnico Radiólogo'), ('administrativo', 'Administrativo'), ('enfermeria', 'Enfermería'), ('otro', 'Otro')], help_text='Rol principal del usuario en el servicio', max_length=30, null=True),
        ),
    ]
