# Generated by Django 5.1.4 on 2026-02-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_anio_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trabaja_remoto',
            field=models.BooleanField(default=False, help_text='Médico trabaja a distancia (para cálculo bonus urgencia RM)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(blank=True, choices=[('medico_staff', 'Médico de Staff'), ('medico_residente', 'Médico Residente'), ('jefe_residentes', 'Jefe de Residentes'), ('instructor_residentes', 'Instructor de Residentes'), ('jefe_servicio', 'Jefe de Servicio'), ('cardiologo', 'Cardiólogo'), ('tecnico', 'Técnico Radiólogo'), ('administrativo', 'Administrativo'), ('enfermeria', 'Enfermería'), ('otro', 'Otro')], help_text='Rol principal del usuario en el servicio', max_length=30, null=True),
        ),
    ]
