# Generated by Django 5.2.12 on 2026-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_trabaja_remoto_alter_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/'),
        ),
    ]
