# Generated by Django 5.2.12 on 2026-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_demo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anio_residencia',
            field=models.CharField(blank=True, help_text='Año de residencia calculado automáticamente (R1, R2, R3, R4)', max_length=10, null=True),
        ),
    ]
