# Generated by Django 5.1.4 on 2025-12-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegionAnatomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Región Anatómica',
                'verbose_name_plural': 'Regiones Anatómicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del protocolo')),
                ('descripcion', models.TextField(blank=True, help_text='Texto para residentes', verbose_name='Descripción')),
                ('requiere_contraste_ev', models.BooleanField(default=False, verbose_name='Requiere contraste EV')),
                ('requiere_contraste_oral', models.BooleanField(default=False, verbose_name='Requiere contraste oral')),
                ('requiere_ayuno', models.BooleanField(default=True, verbose_name='Requiere ayuno')),
                ('calibre_via_minimo', models.CharField(blank=True, help_text='Ej: 20G, 18G', max_length=20, verbose_name='Calibre vía mínimo')),
                ('sitio_via_preferido', models.CharField(blank=True, help_text='Ej: Fosa antecubital', max_length=100, verbose_name='Sitio vía preferido')),
                ('preparacion_paciente', models.TextField(blank=True, help_text='Instrucciones detalladas de preparación', verbose_name='Preparación del paciente')),
                ('cobertura_global', models.TextField(blank=True, help_text='Límites anatómicos generales del estudio', verbose_name='Cobertura global')),
                ('notas_docentes', models.TextField(blank=True, help_text='Información adicional para residentes', verbose_name='Notas docentes')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='protocolos.modalidad', verbose_name='Modalidad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='protocolos.regionanatomica', verbose_name='Región')),
                ('tags', models.ManyToManyField(blank=True, related_name='protocolos', to='protocolos.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['modalidad', 'region', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FaseAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la fase')),
                ('tipo_fase', models.CharField(choices=[('SIN', 'Sin contraste'), ('ART', 'Arterial'), ('PORT', 'Portal'), ('TARD', 'Tardía'), ('OTRA', 'Otra')], max_length=10, verbose_name='Tipo de fase')),
                ('delay_segundos', models.IntegerField(blank=True, help_text='Delay respecto a inyección de contraste', null=True, verbose_name='Delay (segundos)')),
                ('cobertura_desde', models.CharField(blank=True, help_text='Ej: Apex pulmonar', max_length=100, verbose_name='Cobertura desde')),
                ('cobertura_hasta', models.CharField(blank=True, help_text='Ej: Sínfisis púbica', max_length=100, verbose_name='Cobertura hasta')),
                ('ventanas_recomendadas', models.TextField(blank=True, help_text='Ej: Parénquima, mediastino, ósea', verbose_name='Ventanas recomendadas')),
                ('detalles_tecnicos', models.TextField(blank=True, help_text='kVp, mAs, grosor de corte, etc.', verbose_name='Detalles técnicos')),
                ('notas_para_residente', models.TextField(blank=True, help_text='Información adicional sobre esta fase', verbose_name='Notas para residente')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='protocolos.protocolo', verbose_name='Protocolo')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fases', to='protocolos.regionanatomica', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Fase de Adquisición',
                'verbose_name_plural': 'Fases de Adquisición',
                'ordering': ['orden'],
            },
        ),
    ]
