# Generated by Django 5.1.4 on 2025-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('dni_paciente', models.CharField(max_length=20)),
                ('sector_solicitante', models.CharField(max_length=100)),
                ('medico_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_estudio', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('emitido', 'Pedido emitido'), ('recibido', 'Pedido recibido'), ('realizado', 'Estudio realizado')], default='emitido', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
