# Generated by Django 5.1.4 on 2026-02-15 00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('historia_clinica', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('obra_social', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_afiliado', models.CharField(blank=True, max_length=100, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('habitacion', models.CharField(blank=True, max_length=20, null=True)),
                ('cama', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente de Estudio',
                'verbose_name_plural': 'Pacientes de Estudios',
                'db_table': 'pedidos_pacientes_estudio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_solicitante', models.CharField(max_length=255)),
                ('descripcion_estudio', models.TextField(help_text='Descripción del estudio solicitado (texto libre del email)')),
                ('indicacion_clinica', models.TextField(blank=True, help_text='Motivo o indicación clínica del estudio')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'En Procesamiento'), ('PROGRAMADO', 'Programado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error en Procesamiento')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('NORMAL', 'Normal'), ('BAJA', 'Baja')], default='NORMAL', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('email_message_id', models.CharField(blank=True, help_text='Message-ID del email original', max_length=255, unique=True)),
                ('email_asunto', models.CharField(blank=True, max_length=500)),
                ('email_remitente', models.EmailField(blank=True, max_length=254)),
                ('email_fecha', models.DateTimeField(blank=True, null=True)),
                ('datos_raw', models.JSONField(blank=True, default=dict, help_text='Datos crudos del email para análisis posterior')),
                ('procesado_automaticamente', models.BooleanField(default=False)),
                ('requiere_revision', models.BooleanField(default=True, help_text='Indica si requiere revisión manual antes de procesar')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('medico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_asignados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos_estudios.pacienteestudio')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Estudio',
                'verbose_name_plural': 'Pedidos de Estudios',
                'db_table': 'pedidos_estudios',
                'ordering': ['-fecha_solicitud', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='LogProcesamientoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(max_length=255)),
                ('email_asunto', models.CharField(max_length=500)),
                ('email_remitente', models.EmailField(max_length=254)),
                ('email_fecha', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error'), ('PARCIAL', 'Procesamiento Parcial'), ('DUPLICADO', 'Email Duplicado')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('datos_extraidos', models.JSONField(blank=True, default=dict, help_text='Datos extraídos del email')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de errores encontrados')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento', models.FloatField(default=0, help_text='Tiempo de procesamiento en segundos')),
                ('pedido_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_procesamiento', to='pedidos_estudios.pedidoestudio')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'db_table': 'pedidos_log_procesamiento',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='pedidos_estudios/adjuntos/%Y/%m/')),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamaño', models.IntegerField(help_text='Tamaño en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='pedidos_estudios.pedidoestudio')),
            ],
            options={
                'verbose_name': 'Adjunto de Email',
                'verbose_name_plural': 'Adjuntos de Emails',
                'db_table': 'pedidos_adjuntos_email',
            },
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('modalidad', models.CharField(choices=[('RX', 'Radiografía'), ('TC', 'Tomografía Computada'), ('RM', 'Resonancia Magnética'), ('US', 'Ecografía'), ('MN', 'Medicina Nuclear'), ('OT', 'Otros')], default='OT', max_length=2)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, unique=True)),
                ('email_notificacion', models.EmailField(blank=True, help_text='Email alternativo para notificaciones de este tipo de estudio', max_length=254)),
                ('requiere_preparacion', models.BooleanField(default=False)),
                ('tiempo_estimado', models.IntegerField(default=30, help_text='Tiempo estimado en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('medico_responsable', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Staff Médico', 'Médicos']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Estudio',
                'verbose_name_plural': 'Tipos de Estudios',
                'db_table': 'pedidos_tipos_estudio',
                'ordering': ['modalidad', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedidoestudio',
            name='tipo_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos_estudios.tipoestudio'),
        ),
        migrations.AddIndex(
            model_name='pedidoestudio',
            index=models.Index(fields=['-fecha_solicitud'], name='pedidos_est_fecha_s_732ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoestudio',
            index=models.Index(fields=['estado'], name='pedidos_est_estado_f42853_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoestudio',
            index=models.Index(fields=['email_message_id'], name='pedidos_est_email_m_1b5845_idx'),
        ),
    ]
