# Generated by Django 5.1.4 on 2025-04-28 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoestudio',
            name='apellido_paciente',
        ),
        migrations.RemoveField(
            model_name='pedidoestudio',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='pedidoestudio',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoestudio',
            name='tipo_estudio',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='PedidoEstudioNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedidos_estudios.pedidoestudio')),
            ],
        ),
    ]
