# Generated by Django 5.1.4 on 2026-02-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoestudio',
            name='indicacion_clinica',
            field=models.TextField(blank=True, default='', help_text='Motivo o indicación clínica del estudio'),
        ),
        migrations.AlterField(
            model_name='pedidoestudio',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
