# Generated by Django 4.2.25 on 2026-02-15 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos_estudios', '0002_alter_pedidoestudio_indicacion_clinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del médico', max_length=255)),
                ('matricula', models.CharField(blank=True, help_text='Número de matrícula provincial/nacional', max_length=50)),
                ('especialidad', models.CharField(choices=[('DOPPLER', 'Ecodoppler'), ('ECOCARDIO', 'Ecocardiograma'), ('AMBOS', 'Doppler y Ecocardio')], default='AMBOS', help_text='Tipo de estudios que puede realizar', max_length=20)),
                ('email', models.EmailField(help_text='Email para notificaciones', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50)),
                ('whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp (con código de país)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si está actualmente disponible para recibir asignaciones')),
                ('orden_rotacion', models.IntegerField(default=0, help_text='Orden en la rotación (para asignación automática futura)')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el médico (horarios especiales, etc.)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuario del sistema (si está registrado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_guardia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico de Guardia',
                'verbose_name_plural': 'Médicos de Guardia',
                'db_table': 'pedidos_medicos_guardia',
                'ordering': ['especialidad', 'orden_rotacion', 'nombre_completo'],
            },
        ),
    ]
