# Generated by Django 5.1.4 on 2025-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0002_remove_pedidoestudio_apellido_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoestudio',
            name='modalidad',
            field=models.CharField(choices=[('TC', 'Tomografía Computada'), ('RM', 'Resonancia Magnética'), ('ECO', 'Ecografía')], default='TC', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidoestudio',
            name='prioridad',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
