# Generated by Django 5.1.4 on 2025-05-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0003_pedidoestudio_modalidad_pedidoestudio_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPedidoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.CharField(choices=[('estado', 'Cambio de estado'), ('prioridad', 'Cambio de prioridad'), ('modalidad', 'Cambio de modalidad'), ('visualizacion', 'Visualización del pedido'), ('otro', 'Otro cambio')], max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('es_visualizacion', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos_estudios.pedidoestudio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
