# Generated by Django 4.2.25 on 2026-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0003_medicoguardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoguardia',
            name='token_acceso',
            field=models.CharField(blank=True, help_text='Token único para acceder sin login (generado automáticamente)', max_length=64, null=True, unique=True),
        ),
    ]
