# Generated by Django 5.1.4 on 2025-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0004_historialpedidoestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoestudio',
            name='modalidad',
            field=models.CharField(choices=[('TC', 'Tomografía Computada'), ('RM', 'Resonancia Magnética'), ('ECO', 'Ecografía'), ('RX', 'Radiografía')], default='TC', max_length=3),
        ),
    ]
