# Generated by Django 5.1.4 on 2025-05-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_estudios', '0005_alter_pedidoestudio_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
    ]
