# Generated by Django 4.2.25 on 2025-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre identificativo del equipo (ej: 'Tomógrafo Principal')", max_length=200)),
                ('area', models.CharField(choices=[('TOM', 'Tomografía'), ('RM', 'Resonancia Magnética'), ('RX', 'Radiología'), ('ECO', 'Ecografía'), ('OTRO', 'Otro')], default='OTRO', help_text='Área del servicio a la que pertenece', max_length=10)),
                ('fabricante', models.CharField(blank=True, help_text='Fabricante del equipo (ej: Siemens, Philips, GE)', max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, help_text='Modelo específico del equipo', max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del equipo', max_length=100, null=True, verbose_name='Número de serie')),
                ('ubicacion', models.CharField(blank=True, help_text="Ubicación física del equipo (ej: 'Piso 2, Sala A')", max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_instalacion', models.DateField(blank=True, help_text='Fecha en que se instaló el equipo', null=True, verbose_name='Fecha de instalación')),
                ('ultimo_mantenimiento', models.DateField(blank=True, help_text='Fecha del último mantenimiento realizado', null=True, verbose_name='Último mantenimiento')),
                ('en_servicio', models.BooleanField(default=True, help_text='¿El equipo está actualmente en servicio?')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el equipo', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Equipo de Imágenes',
                'verbose_name_plural': 'Equipos de Imágenes',
                'ordering': ['area', 'nombre'],
                'indexes': [models.Index(fields=['area', 'en_servicio'], name='equipos_equ_area_a73d09_idx')],
            },
        ),
    ]
