# Generated by Django 5.1.4 on 2024-12-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudio',
            options={'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.AlterModelOptions(
            name='ordenmedica',
            options={'verbose_name': 'Orden Médica', 'verbose_name_plural': 'Órdenes médicas'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='registroatencion',
            options={'verbose_name': 'Registro de atención', 'verbose_name_plural': 'Registros de atención'},
        ),
    ]
