# Generated by Django 4.2.25 on 2025-12-29 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_filas', models.IntegerField(default=0)),
                ('total_ingresos_unicos', models.IntegerField(default=0)),
                ('total_estudios_candidatos', models.IntegerField(default=0)),
                ('total_estudios_finalizados', models.IntegerField(default=0)),
                ('total_tc', models.IntegerField(default=0)),
                ('total_rm', models.IntegerField(default=0)),
                ('total_rx', models.IntegerField(default=0)),
                ('total_eco', models.IntegerField(default=0)),
                ('total_otros', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_eges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importación EGES',
                'verbose_name_plural': 'Lotes de importación EGES',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='EgesRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('hora_turno', models.TimeField(blank=True, null=True)),
                ('centro_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('historia_clinica', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio', models.CharField(blank=True, max_length=200, null=True)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_turno', models.CharField(blank=True, max_length=50, null=True)),
                ('es_insumo', models.BooleanField(default=False)),
                ('modalidad', models.CharField(choices=[('TC', 'Tomografía'), ('RM', 'Resonancia Magnética'), ('RX', 'Rayos X'), ('ECO', 'Ecografía'), ('OTROS', 'Otros')], default='OTROS', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='eges_import.importbatch')),
            ],
            options={
                'verbose_name': 'Fila EGES',
                'verbose_name_plural': 'Filas EGES',
                'ordering': ['batch', 'fecha_turno', 'hora_turno'],
                'indexes': [models.Index(fields=['batch', 'historia_clinica', 'fecha_turno'], name='eges_import_batch_i_2aece7_idx'), models.Index(fields=['batch', 'modalidad', 'estado_turno'], name='eges_import_batch_i_fd4863_idx')],
            },
        ),
    ]
