# Generated by Django 4.2.25 on 2025-12-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0003_remove_duplicates_before_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='egesrow',
            unique_together={('historia_clinica', 'fecha_turno', 'hora_turno', 'centro_atencion', 'servicio')},
        ),
    ]
