# Generated by Django 5.2.12 on 2026-03-15 14:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0002_add_unique_constraint_prevent_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_etiqueta', models.CharField(default='Director', help_text='Etiqueta descriptiva para identificar este token (ej: "Director 2026")', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Token de Director',
                'verbose_name_plural': 'Tokens de Director',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='egesrow',
            name='medico_informante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='sub_modalidad',
            field=models.CharField(blank=True, choices=[('ECOCARDIO', 'Ecocardiograma'), ('DOPPLER', 'Doppler / Dúplex'), ('ECO_MAMA', 'Ecografía Mamaria'), ('ECO_TIROIDES', 'Ecografía Tiroidea'), ('ECO_OBSTETRICA', 'Ecografía Obstétrica'), ('ECO_PELVIS', 'Ecografía Pelviana'), ('ECO_ABDOMINAL', 'Ecografía Abdominal'), ('ECO_NEONATAL', 'Ecografía Neonatal'), ('ECO_PARTES_BLANDAS', 'Ecografía Partes Blandas')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='total_dx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='total_mam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='egesrow',
            name='modalidad',
            field=models.CharField(choices=[('TC', 'Tomografía Computada'), ('RM', 'Resonancia Magnética'), ('RX', 'Rayos X / Radiología'), ('DX', 'Densitometría'), ('MAM', 'Mamografía'), ('ECO', 'Ecografía'), ('OTROS', 'Otros')], default='OTROS', max_length=10),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['fecha_turno', 'modalidad'], name='eges_import_fecha_t_3d0d00_idx'),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['medico_informante', 'fecha_turno'], name='eges_import_medico__c67d49_idx'),
        ),
    ]
