# Generated by Django 4.2.25 on 2025-12-29 02:07

from django.db import migrations


def remove_duplicate_rows(apps, schema_editor):
    """
    Elimina filas duplicadas de EgesRow manteniendo solo la primera aparición.
    Los duplicados se identifican por: HC + Fecha + Hora + Centro + Servicio
    """
    EgesRow = apps.get_model('eges_import', 'EgesRow')
    
    # Encontrar duplicados usando consulta SQL raw
    from django.db import connection
    with connection.cursor() as cursor:
        # Encontrar IDs de filas duplicadas (todas excepto la primera)
        cursor.execute("""
            SELECT id
            FROM eges_import_egesrow
            WHERE id NOT IN (
                SELECT MIN(id)
                FROM eges_import_egesrow
                GROUP BY historia_clinica, fecha_turno, hora_turno, centro_atencion, servicio
            )
        """)
        
        duplicate_ids = [row[0] for row in cursor.fetchall()]
    
    if duplicate_ids:
        deleted_count = EgesRow.objects.filter(id__in=duplicate_ids).delete()[0]
        print(f"[EGES Migration] Eliminados {deleted_count} registros duplicados")
    else:
        print("[EGES Migration] No se encontraron duplicados")


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_rows, reverse_code=migrations.RunPython.noop),
    ]
