# Generated by Django 5.2.12 on 2026-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0003_nuevas_modalidades_submodalidad_medico_directortoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='egesrow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='codigo_obra_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='codigo_practica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='obra_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='practica',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='egesrow',
            unique_together={('historia_clinica', 'fecha_turno', 'hora_turno', 'centro_atencion', 'practica')},
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['obra_social', 'fecha_turno'], name='eges_import_obra_so_71f3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['codigo_practica'], name='eges_import_codigo__6ee05a_idx'),
        ),
    ]
