# Generated by Django 5.2.12 on 2026-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0004_practica_obrasocial_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código RNOS')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nombre Obra Social',
                'verbose_name_plural': 'Nombres Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
    ]
