# Generated by Django 5.2.12 on 2026-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0005_nombreobrasocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='total_rx_sin_informe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='total_serie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='egesrow',
            name='modalidad',
            field=models.CharField(choices=[('TC', 'Tomografía Computada'), ('RM', 'Resonancia Magnética'), ('RX', 'Rayos X / Radiología'), ('DX', 'Densitometría'), ('MAM', 'Mamografía'), ('ECO', 'Ecografía'), ('SERIE', 'Seriografía'), ('OTROS', 'Otros')], default='OTROS', max_length=10),
        ),
    ]
