# Generated by Django 5.2.12 on 2026-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eges_import', '0006_add_serie_modalidad_rx_sin_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='egesrow',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='estado_informe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='hora_hasta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='medico_actuante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='region_informe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='tipo_atencion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='tipo_paciente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='egesrow',
            name='tipo_turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['medico_actuante', 'fecha_turno'], name='eges_import_medico__0c5316_idx'),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['dni_paciente', 'fecha_turno'], name='eges_import_dni_pac_64bee2_idx'),
        ),
        migrations.AddIndex(
            model_name='egesrow',
            index=models.Index(fields=['tipo_atencion', 'fecha_turno'], name='eges_import_tipo_at_a3dcdf_idx'),
        ),
    ]
