# Generated by Django 4.2.25 on 2026-01-07 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Plantilla base del preinforme. Use {HALLAZGOS} para marcar donde el residente debe escribir.')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Preinforme',
                'verbose_name_plural': 'Plantillas de Preinformes',
                'ordering': ['tipo_estudio__nombre', 'region__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Preinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudio', models.CharField(help_text='Número del estudio en el sistema EGES', max_length=50)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad_paciente', models.PositiveIntegerField()),
                ('sexo_paciente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('tecnica', models.TextField(help_text='Descripción de la técnica utilizada')),
                ('hallazgos', models.TextField(help_text='Hallazgos encontrados por el residente')),
                ('conclusion', models.TextField(help_text='Conclusión del residente')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_revision', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('revisado', 'Revisado'), ('finalizado', 'Finalizado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('plantilla_utilizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preinformes.plantillapreinforme')),
            ],
            options={
                'verbose_name': 'Preinforme',
                'verbose_name_plural': 'Preinformes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Estudio',
                'verbose_name_plural': 'Tipos de Estudios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RevisionPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica_corregida', models.TextField(blank=True, help_text='Correcciones en la técnica', null=True)),
                ('hallazgos_corregidos', models.TextField(blank=True, help_text='Correcciones en los hallazgos', null=True)),
                ('conclusion_corregida', models.TextField(blank=True, help_text='Correcciones en la conclusión', null=True)),
                ('comentarios_generales', models.TextField(blank=True, help_text='Comentarios y sugerencias para el residente', null=True)),
                ('puntuacion', models.PositiveIntegerField(blank=True, help_text='Puntuación del 1 al 10 (opcional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('informe_final', models.TextField(help_text='Versión final del informe para copiar a EGES')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('preinforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='preinformes.preinforme')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión de Preinforme',
                'verbose_name_plural': 'Revisiones de Preinformes',
            },
        ),
        migrations.AddField(
            model_name='preinforme',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinformes.region'),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinformes_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinformes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='tipo_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinformes.tipoestudio'),
        ),
        migrations.AddField(
            model_name='plantillapreinforme',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinformes.region'),
        ),
        migrations.AddField(
            model_name='plantillapreinforme',
            name='tipo_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinformes.tipoestudio'),
        ),
        migrations.CreateModel(
            name='HistorialEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_preinformes', models.PositiveIntegerField(default=0)),
                ('preinformes_finalizados', models.PositiveIntegerField(default=0)),
                ('promedio_puntuacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fecha_ultimo_preinforme', models.DateTimeField(blank=True, null=True)),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estudios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estudios',
                'verbose_name_plural': 'Historiales de Estudios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='plantillapreinforme',
            unique_together={('nombre', 'tipo_estudio', 'region')},
        ),
    ]
