# Generated by Django 4.2.25 on 2026-01-07 03:27

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinforme',
            name='dni_paciente',
            field=models.CharField(blank=True, default='00000000', help_text='DNI o documento de identidad del paciente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='conclusion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Conclusión del residente'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='hallazgos',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Hallazgos encontrados por el residente'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='tecnica',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción de la técnica utilizada'),
        ),
    ]
