# Generated by Django 5.1.4 on 2026-01-07 03:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0002_preinforme_dni_paciente_alter_preinforme_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillapreinforme',
            name='conclusion_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Plantilla para la sección de conclusión', verbose_name='Plantilla de Conclusión'),
        ),
        migrations.AddField(
            model_name='plantillapreinforme',
            name='hallazgos_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Plantilla para la sección de hallazgos', verbose_name='Plantilla de Hallazgos'),
        ),
        migrations.AddField(
            model_name='plantillapreinforme',
            name='tecnica_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Plantilla para la sección de técnica', verbose_name='Plantilla de Técnica'),
        ),
        migrations.AlterField(
            model_name='plantillapreinforme',
            name='contenido',
            field=models.TextField(blank=True, help_text='Plantilla base del preinforme (campo legacy)'),
        ),
    ]
