# Generated by Django 5.1.4 on 2026-01-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0003_plantillapreinforme_conclusion_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinforme',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
