# Generated by Django 5.1.4 on 2026-01-07 04:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0004_preinforme_fecha_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='conclusion_corregida',
        ),
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='hallazgos_corregidos',
        ),
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='tecnica_corregida',
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='conclusion_staff',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Versión editada de la conclusión', verbose_name='Conclusión (versión staff)'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='hallazgos_staff',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Versión editada de los hallazgos', verbose_name='Hallazgos (versión staff)'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='tecnica_staff',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Versión editada de la técnica', verbose_name='Técnica (versión staff)'),
        ),
        migrations.AlterField(
            model_name='revisionpreinforme',
            name='informe_final',
            field=models.TextField(blank=True, help_text='Versión final del informe para copiar a EGES (generado automáticamente)'),
        ),
    ]
