# Generated by Django 4.2.25 on 2026-01-07 04:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0005_remove_revisionpreinforme_conclusion_corregida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='conclusion_staff',
        ),
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='hallazgos_staff',
        ),
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='informe_final',
        ),
        migrations.RemoveField(
            model_name='revisionpreinforme',
            name='tecnica_staff',
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='informe_final_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Informe final editado por el staff - se inicializa con el contenido del residente', verbose_name='Informe Final (Staff)'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='informe_residente_snapshot',
            field=models.TextField(blank=True, help_text='Snapshot del informe completo del residente al momento de la revisión'),
        ),
    ]
