# Generated by Django 4.2.25 on 2026-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0006_remove_revisionpreinforme_conclusion_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillapreinforme',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador (Solo yo)'), ('publica', 'Pública (Todos)')], default='borrador', max_length=20),
        ),
    ]
