# Generated by Django 4.2.25 on 2026-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0007_plantillapreinforme_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillapreinforme',
            name='sistema_destino',
            field=models.CharField(choices=[('eges', 'EGES (con acentos y ñ)'), ('netterm', 'Netterm (sin acentos ni ñ)'), ('universal', 'Universal (ambos sistemas)')], default='universal', help_text='Sistema para el que está diseñada esta plantilla', max_length=20, verbose_name='Sistema destino'),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='sistema_destino',
            field=models.CharField(choices=[('eges', 'EGES'), ('netterm', 'Netterm')], default='eges', help_text='Sistema donde se cargará este informe', max_length=20, verbose_name='Sistema destino'),
        ),
    ]
