# Generated by Django 5.1.4 on 2026-01-09 01:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0008_plantillapreinforme_sistema_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinforme',
            name='conclusion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Conclusión del residente'),
        ),
    ]
