# Generated by Django 4.2.25 on 2026-01-09 03:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0009_alter_preinforme_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinforme',
            name='informe_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Informe completo del residente en formato HTML enriquecido', null=True, verbose_name='Informe completo (HTML)'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='conclusion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Conclusión del residente', null=True),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='hallazgos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Hallazgos encontrados por el residente', null=True),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='tecnica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción de la técnica utilizada', null=True),
        ),
    ]
