# Generated by Django 4.2.25 on 2026-01-10 21:26

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0010_preinforme_informe_html_alter_preinforme_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillapreinforme',
            name='conclusion_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'contenido' en su lugar", null=True, verbose_name='[LEGACY] Plantilla de Conclusión'),
        ),
        migrations.AlterField(
            model_name='plantillapreinforme',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Contenido completo de la plantilla con formato. Pega directamente desde Word.', verbose_name='Contenido de la Plantilla'),
        ),
        migrations.AlterField(
            model_name='plantillapreinforme',
            name='hallazgos_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'contenido' en su lugar", null=True, verbose_name='[LEGACY] Plantilla de Hallazgos'),
        ),
        migrations.AlterField(
            model_name='plantillapreinforme',
            name='tecnica_template',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'contenido' en su lugar", null=True, verbose_name='[LEGACY] Plantilla de Técnica'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='conclusion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'informe_html' en su lugar", null=True, verbose_name='[LEGACY] Conclusión'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='hallazgos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'informe_html' en su lugar", null=True, verbose_name='[LEGACY] Hallazgos'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='informe_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Informe completo con formato. Incluye técnica, hallazgos y conclusión.', null=True, verbose_name='Contenido del Preinforme'),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='tecnica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Campo legacy - usar 'informe_html' en su lugar", null=True, verbose_name='[LEGACY] Técnica'),
        ),
    ]
