# Generated by Django 4.2.25 on 2026-01-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preinformes', '0012_migrar_datos_campo_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal (ej: #3B82F6)', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Preinforme',
                'verbose_name_plural': 'Etiquetas de Preinformes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='preinforme',
            name='en_edicion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinformes_editando', to=settings.AUTH_USER_MODEL, verbose_name='En edición por'),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='ultima_actividad_edicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad de edición'),
        ),
        migrations.AddConstraint(
            model_name='plantillapreinforme',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'publica')), fields=('nombre', 'tipo_estudio', 'region', 'sistema_destino'), name='unique_plantilla_publica'),
        ),
        migrations.AddField(
            model_name='etiquetapreinforme',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preinforme',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='preinformes', to='preinformes.etiquetapreinforme', verbose_name='Etiquetas clínicas'),
        ),
    ]
