# Generated by Django 4.2.25 on 2026-01-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0013_agregar_etiquetas_y_bloqueo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinforme',
            name='dni_paciente',
            field=models.CharField(blank=True, help_text='DNI o documento de identidad del paciente', max_length=20, null=True),
        ),
    ]
