# Generated by Django 4.2.25 on 2026-01-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0014_alter_preinforme_dni_paciente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantillapreinforme',
            unique_together=set(),
        ),
    ]
