# Generated by Django 5.1.4 on 2026-02-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0015_remove_unique_together_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinforme',
            name='edad_paciente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preinforme',
            name='sexo_paciente',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
