# Generated by Django 5.2.12 on 2026-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0016_alter_preinforme_edad_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinforme',
            name='asignacion_compartida',
            field=models.BooleanField(default=False, help_text='Si está activado, el estudio estará en el pool compartido para jefes/instructores', verbose_name='Asignación compartida'),
        ),
    ]
