# Generated by Django 5.2.12 on 2026-03-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0017_preinforme_asignacion_compartida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAsistentePreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('preinforme', models.ForeignKey(blank=True, help_text='Preinforme asociado a la conversación (null si aún no fue guardado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_asistente', to='preinformes.preinforme')),
                ('usuario', models.ForeignKey(help_text='Residente que mantiene la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_asistente_preinforme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación con Asistente de Preinforme',
                'verbose_name_plural': 'Conversaciones con Asistente de Preinforme',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistentePreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Residente'), ('assistant', 'Asistente IA')], max_length=10)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, choices=[('positivo', 'Positivo 👍'), ('negativo', 'Negativo 👎')], max_length=10, null=True)),
                ('conversacion', models.ForeignKey(help_text='Conversación a la que pertenece este mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_asistente', to='preinformes.conversacionasistentepreinforme')),
            ],
            options={
                'verbose_name': 'Mensaje del Asistente de Preinforme',
                'verbose_name_plural': 'Mensajes del Asistente de Preinforme',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionasistentepreinforme',
            index=models.Index(fields=['-fecha_actualizacion'], name='preinformes_fecha_a_223719_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionasistentepreinforme',
            index=models.Index(fields=['usuario', '-fecha_actualizacion'], name='preinformes_usuario_c9a29b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeasistentepreinforme',
            index=models.Index(fields=['conversacion', 'timestamp'], name='preinformes_convers_a7e636_idx'),
        ),
    ]
