# Generated by Django 5.2.12 on 2026-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0018_asistente_ia_preinforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionasistentepreinforme',
            name='evaluacion_ia',
            field=models.JSONField(blank=True, default=dict, help_text='Evaluación de la sesión: {razonamiento_clinico, terminologia, autonomia, receptividad, comentario}'),
        ),
        migrations.AddField(
            model_name='conversacionasistentepreinforme',
            name='evaluada',
            field=models.BooleanField(default=False, help_text='Si la conversación fue evaluada por la IA'),
        ),
        migrations.AddField(
            model_name='conversacionasistentepreinforme',
            name='puntuacion_global',
            field=models.FloatField(blank=True, help_text='Puntaje global de la sesión (0–10)', null=True),
        ),
    ]
