# Generated by Django 5.2.12 on 2026-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0019_scoring_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionasistentepreinforme',
            name='evaluacion_publicada',
            field=models.BooleanField(default=False, help_text='Si el docente habilitó que el residente vea su evaluación'),
        ),
    ]
