# Generated by Django 5.2.12 on 2026-04-02 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0020_evaluacion_publicada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('anonimizar', models.BooleanField(default=False, help_text='Si marcás esta opción, tus respuestas aparecerán sin tu nombre en los resultados.', verbose_name='Anonimizar mis respuestas en el reporte')),
                ('p1_usabilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='El sistema es fácil de usar')),
                ('p2_acceso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Acceder desde mi dispositivo es cómodo')),
                ('p3_feedback_util', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Los comentarios del staff fueron útiles para mi aprendizaje')),
                ('p4_feedback_oportuno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='El feedback fue oportuno (llegó en tiempo razonable)')),
                ('p5_mejora_redaccion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Siento que mejoré mi redacción de informes usando el sistema')),
                ('p6_banco_informes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='El banco de informes me ayudó como referencia')),
                ('p_contexto_previo', models.TextField(blank=True, default='', help_text='Si ingresaste directo al sistema, describí cómo imaginás que sería sin él.', verbose_name='¿Cómo era tu flujo de trabajo con los preinformes antes de usar este sistema?')),
                ('p7_comparacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comparando con lo que describiste, este sistema mejoró mi proceso de trabajo')),
                ('p8_ia_asistente', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='El asistente IA (Radiólogo Mentor) fue útil')),
                ('p9_supervision', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='La supervisión del staff se volvió más estructurada')),
                ('p10_recomendacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Recomendaría este sistema a otros servicios de residencia')),
                ('p_util', models.TextField(blank=True, default='', verbose_name='¿Qué fue lo más útil del sistema?')),
                ('p_mejora', models.TextField(blank=True, default='', verbose_name='¿Qué cambiarías o agregarías?')),
                ('analisis_ia', models.JSONField(blank=True, help_text='Se guarda el último análisis generado por IA para los resultados globales.', null=True, verbose_name='Análisis IA del conjunto de encuestas')),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preinformes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta de uso del sistema',
                'verbose_name_plural': 'Encuestas de uso del sistema',
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
