# Generated by GitHub Copilot

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import preinformes.models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0021_encuesta_residente_cadi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=preinformes.models.upload_adjunto_preinforme, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen')),
                ('origen', models.CharField(choices=[('residente', 'Residente'), ('revisor', 'Revisor')], max_length=20)),
                ('descripcion_corta', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('preinforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='preinformes.preinforme')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_preinformes_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de Preinforme',
                'verbose_name_plural': 'Adjuntos de Preinformes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='adjuntopreinforme',
            index=models.Index(fields=['preinforme', 'origen', '-fecha_creacion'], name='preinforme_p_origen_4b0fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='adjuntopreinforme',
            index=models.Index(fields=['subido_por', '-fecha_creacion'], name='preinforme_subido__eece73_idx'),
        ),
    ]
