# Generated by Django 5.2.12 on 2026-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0022_adjuntopreinforme'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adjuntopreinforme',
            new_name='preinformes_preinfo_d8ef70_idx',
            old_name='preinforme_p_origen_4b0fd5_idx',
        ),
        migrations.RenameIndex(
            model_name='adjuntopreinforme',
            new_name='preinformes_subido__33cb30_idx',
            old_name='preinforme_subido__eece73_idx',
        ),
    ]
