# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0023_rename_preinforme_p_origen_4b0fd5_idx_preinformes_preinfo_d8ef70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionpreinforme',
            name='resumen_ia_revision',
            field=models.JSONField(blank=True, default=dict, help_text='Resumen IA orientativo para el staff antes de revisar'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='resumen_ia_revision_generado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de generacion del resumen IA pre-revision', null=True),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='resumen_ia_revision_error',
            field=models.TextField(blank=True, default='', help_text='Ultimo error al generar el resumen IA pre-revision'),
        ),
    ]
