# Generated by Django 5.2.12 on 2026-07-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0024_resumen_ia_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinforme',
            name='contexto_clinico',
            field=models.TextField(blank=True, default='', help_text='Dato clinico, motivo del estudio o pregunta a responder. Opcional.', verbose_name='Contexto clinico'),
        ),
    ]
