# Generated by Django 5.2.12 on 2026-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0025_preinforme_contexto_clinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionpreinforme',
            name='evaluacion_ia_final',
            field=models.JSONField(blank=True, default=dict, help_text='Evaluacion IA formativa generada al finalizar la revision'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='evaluacion_ia_final_error',
            field=models.TextField(blank=True, default='', help_text='Ultimo error al generar la evaluacion IA final'),
        ),
        migrations.AddField(
            model_name='revisionpreinforme',
            name='evaluacion_ia_final_generada_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de generacion de la evaluacion IA final', null=True),
        ),
    ]
