# Generated by Django 5.2.12 on 2026-07-25 23:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('preinformes', '0027_preinforme_es_registro_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaPlantillaPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('nueva', 'Nueva plantilla'), ('modificacion', 'Modificación de plantilla vigente')], default='nueva', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador generado'), ('pendiente', 'Pendiente de revisión'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=20)),
                ('estudio_especifico', models.CharField(max_length=200)),
                ('instruccion_usuario', models.TextField(blank=True, default='')),
                ('titulo', models.CharField(max_length=500)),
                ('encabezado', models.TextField()),
                ('hallazgos', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('proveedor_ia', models.CharField(blank=True, default='', max_length=50)),
                ('modelo_ia', models.CharField(blank=True, default='', max_length=100)),
                ('version_instrucciones', models.CharField(blank=True, default='', max_length=50)),
                ('motivo_modificacion', models.TextField(blank=True, default='')),
                ('observacion_revision', models.TextField(blank=True, default='')),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_plantilla_creadas', to=settings.AUTH_USER_MODEL)),
                ('plantilla_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_modificacion', to='preinformes.plantillapreinforme')),
                ('preinforme_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_plantilla_originadas', to='preinformes.preinforme')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preinformes.region')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_plantilla_revisadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preinformes.tipoestudio')),
            ],
            options={
                'verbose_name': 'Propuesta de plantilla de preinforme',
                'verbose_name_plural': 'Propuestas de plantillas de preinformes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VersionPlantillaPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=500)),
                ('encabezado', models.TextField()),
                ('hallazgos', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('motivo_cambio', models.TextField(blank=True, default='')),
                ('fecha_aprobacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_plantilla_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_institucionales', to='preinformes.plantillapreinforme')),
                ('propuesta_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_publicada', to='preinformes.propuestaplantillapreinforme')),
            ],
            options={
                'verbose_name': 'Versión de plantilla de preinforme',
                'verbose_name_plural': 'Versiones de plantillas de preinformes',
                'ordering': ['plantilla', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPlantillaPreinforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores_variables', models.JSONField(blank=True, default=dict)),
                ('lateralidad', models.CharField(blank=True, default='', max_length=20)),
                ('contraste_ev', models.BooleanField(blank=True, null=True)),
                ('volumen_contraste_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('contraste_oral', models.BooleanField(blank=True, null=True)),
                ('contenido_renderizado', models.TextField()),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('aplicada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_plantilla_realizadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_plantilla_preinforme', to='equipos.equipoimagen')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_estructuradas', to='preinformes.plantillapreinforme')),
                ('preinforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_plantilla', to='preinformes.preinforme')),
                ('propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='preinformes.propuestaplantillapreinforme')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='preinformes.versionplantillapreinforme')),
            ],
            options={
                'verbose_name': 'Aplicación de plantilla de preinforme',
                'verbose_name_plural': 'Aplicaciones de plantillas de preinformes',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.AddIndex(
            model_name='propuestaplantillapreinforme',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='preinformes_estado_d6bd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='propuestaplantillapreinforme',
            index=models.Index(fields=['tipo_estudio', 'region', 'estado'], name='preinformes_tipo_es_24ed1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='versionplantillapreinforme',
            constraint=models.UniqueConstraint(fields=('plantilla', 'numero'), name='unique_numero_version_plantilla_preinforme'),
        ),
        migrations.AddConstraint(
            model_name='versionplantillapreinforme',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('plantilla',), name='unique_version_vigente_plantilla_preinforme'),
        ),
    ]
