# Generated by Django 5.2.12 on 2026-07-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinformes', '0028_propuestaplantillapreinforme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionplantillapreinforme',
            name='marca_contraste',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
