# Generated by Django 5.1.4 on 2025-11-30 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('apellido_paciente', models.CharField(max_length=200, verbose_name='Apellido del Paciente')),
                ('dni_paciente', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('edad_paciente', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipo_estudio', models.CharField(choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo de Estudio')),
                ('numero_estudio', models.CharField(blank=True, max_length=50, verbose_name='Número de Estudio')),
                ('fecha_estudio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Estudio')),
                ('region_anatomica', models.CharField(blank=True, max_length=200, verbose_name='Región Anatómica')),
                ('indicacion_clinica', models.TextField(blank=True, verbose_name='Indicación Clínica')),
                ('tecnica', models.TextField(blank=True, verbose_name='Técnica')),
                ('hallazgos', models.TextField(verbose_name='Hallazgos')),
                ('conclusion', models.TextField(verbose_name='Conclusión')),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('REV', 'En Revisión'), ('FIN', 'Finalizado'), ('FIR', 'Firmado')], default='BOR', max_length=3, verbose_name='Estado')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('procesado_con_ia', models.BooleanField(default=False, verbose_name='Procesado con IA')),
                ('confianza_ia', models.FloatField(blank=True, help_text='Nivel de confianza de la IA (0-1)', null=True, verbose_name='Confianza IA')),
                ('sugerencias_ia', models.JSONField(blank=True, default=dict, help_text='Sugerencias de mejora de la IA', verbose_name='Sugerencias IA')),
                ('notas_privadas', models.TextField(blank=True, help_text='Notas privadas del médico (no aparecen en el informe final)', verbose_name='Notas Privadas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_dictados', to=settings.AUTH_USER_MODEL, verbose_name='Médico Informante')),
                ('medico_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_firmados', to=settings.AUTH_USER_MODEL, verbose_name='Médico que Firma')),
            ],
            options={
                'verbose_name': 'Informe Médico',
                'verbose_name_plural': 'Informes Médicos',
                'ordering': ['-fecha_estudio', '-fecha_creacion'],
                'permissions': [('can_dictate', 'Puede dictar informes'), ('can_sign', 'Puede firmar informes'), ('can_use_ai', 'Puede usar IA para informes')],
            },
        ),
        migrations.CreateModel(
            name='AudioTranscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='dictados/%Y/%m/%d/', verbose_name='Archivo de Audio')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('texto_original', models.TextField(blank=True, help_text='Transcripción literal del audio', verbose_name='Texto Original')),
                ('texto_mejorado', models.TextField(blank=True, help_text='Texto mejorado por IA', verbose_name='Texto Mejorado por IA')),
                ('servicio_transcripcion', models.CharField(blank=True, help_text='Whisper, Azure Speech, etc.', max_length=50, verbose_name='Servicio de Transcripción')),
                ('confianza_transcripcion', models.FloatField(blank=True, help_text='Nivel de confianza de la transcripción (0-1)', null=True, verbose_name='Confianza')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Grabación')),
                ('fecha_transcripcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Transcripción')),
                ('grabado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_grabados', to=settings.AUTH_USER_MODEL, verbose_name='Grabado por')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='dictado_informes.informe', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Audio de Dictado',
                'verbose_name_plural': 'Audios de Dictados',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_estudio', models.CharField(choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo de Estudio')),
                ('contenido', models.TextField(verbose_name='Contenido de la Plantilla')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Variables que se pueden completar: {paciente}, {edad}, {fecha}, etc.', verbose_name='Variables')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla de Informe',
                'verbose_name_plural': 'Plantillas de Informes',
                'ordering': ['tipo_estudio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='plantilla_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='dictado_informes.plantillainforme', verbose_name='Plantilla Usada'),
        ),
    ]
