# Generated by Django 4.2.25 on 2025-12-03 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictado_informes', '0007_terminomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminomedico',
            name='termino_correcto',
            field=models.CharField(help_text="Término médico correcto (ej: 'gonartrosis tricompartimental')", max_length=200, verbose_name='Término Correcto'),
        ),
        migrations.AlterField(
            model_name='terminomedico',
            name='termino_incorrecto',
            field=models.CharField(help_text="Término como lo transcribe el navegador (ej: 'con artrosis trick compartimental')", max_length=200, unique=True, verbose_name='Término Incorrecto'),
        ),
        migrations.CreateModel(
            name='CorreccionAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField(help_text='Texto tal como lo transcribió Whisper', verbose_name='Texto original (transcripción Whisper)')),
                ('texto_ia', models.TextField(help_text='Texto después de pasar por la IA en modo FIEL', verbose_name='Texto mejorado por IA')),
                ('texto_final', models.TextField(help_text='Texto después de correcciones manuales del usuario', verbose_name='Texto final (editado por usuario)')),
                ('tipo_estudio', models.CharField(blank=True, choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo de Estudio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de corrección')),
                ('cambios_detectados', models.JSONField(blank=True, default=list, help_text="Lista de cambios: [{de: 'texto_ia', a: 'texto_final', tipo: 'correcion/agregado/eliminado'}]", verbose_name='Cambios detectados')),
                ('fue_aplicada', models.BooleanField(default=False, help_text='Si esta corrección ya fue usada para entrenar/ajustar la IA', verbose_name='Aplicada al modelo')),
                ('votos_utilidad', models.IntegerField(default=0, help_text='Para rankear qué correcciones son más importantes', verbose_name='Votos de utilidad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_aprendizaje', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Corrección de Aprendizaje',
                'verbose_name_plural': 'Correcciones de Aprendizaje',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='dictado_inf_fecha_c_4193c3_idx'), models.Index(fields=['fue_aplicada'], name='dictado_inf_fue_apl_16d8ee_idx')],
            },
        ),
    ]
