# Generated by Django 4.2.25 on 2026-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0008_alter_terminomedico_termino_correcto_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='correccionaprendizaje',
            index=models.Index(fields=['usuario', '-fecha_creacion'], name='dictado_inf_usuario_dd7b49_idx'),
        ),
    ]
