# Generated by Django 5.2.12 on 2026-03-08 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0009_correccionaprendizaje_dictado_inf_usuario_dd7b49_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('tiempo_transcripcion_ms', models.IntegerField(blank=True, help_text='Tiempo de API Whisper (null si usó caché)', null=True, verbose_name='Tiempo Transcripción (ms)')),
                ('tiempo_mejora_ms', models.IntegerField(blank=True, help_text='Tiempo de API GPT/Groq (null si usó caché)', null=True, verbose_name='Tiempo Mejora IA (ms)')),
                ('tiempo_total_ms', models.IntegerField(help_text='Tiempo end-to-end medido por el cliente', verbose_name='Tiempo Total (ms)')),
                ('transcripcion_from_cache', models.BooleanField(default=False, verbose_name='Transcripción desde Caché')),
                ('mejora_from_cache', models.BooleanField(default=False, verbose_name='Mejora desde Caché')),
                ('duracion_audio_segundos', models.FloatField(blank=True, null=True, verbose_name='Duración Audio (segundos)')),
                ('tamanio_audio_kb', models.IntegerField(blank=True, null=True, verbose_name='Tamaño Audio (KB)')),
                ('longitud_transcripcion', models.IntegerField(default=0, verbose_name='Longitud Transcripción (caracteres)')),
                ('longitud_mejora', models.IntegerField(default=0, verbose_name='Longitud Mejora (caracteres)')),
                ('tuvo_errores', models.BooleanField(default=False, verbose_name='¿Tuvo Errores?')),
                ('error_detalle', models.TextField(blank=True, help_text='Stack trace o mensaje de error', verbose_name='Detalle del Error')),
                ('api_transcripcion', models.CharField(choices=[('whisper', 'OpenAI Whisper'), ('groq_whisper', 'Groq Whisper')], default='whisper', max_length=20, verbose_name='API de Transcripción')),
                ('api_mejora', models.CharField(choices=[('gpt', 'OpenAI GPT'), ('groq', 'Groq Llama')], default='gpt', max_length=20, verbose_name='API de Mejora')),
                ('modo_mejora', models.CharField(blank=True, choices=[('FIEL', 'Fiel al Dictado'), ('LIBRE', 'Reescritura Libre'), ('PLANTILLA', 'Con Plantilla')], max_length=20, verbose_name='Modo de Mejora')),
                ('tipo_estudio', models.CharField(blank=True, choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo de Estudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_dictado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Métrica de Dictado',
                'verbose_name_plural': 'Métricas de Dictado',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='dictado_inf_fecha_bf69e8_idx'), models.Index(fields=['usuario', '-fecha'], name='dictado_inf_usuario_cde15f_idx'), models.Index(fields=['tuvo_errores', '-fecha'], name='dictado_inf_tuvo_er_e02739_idx'), models.Index(fields=['fecha', 'tiempo_total_ms'], name='dictado_inf_fecha_eb8a17_idx')],
            },
        ),
    ]
