# Generated by Django 5.2.12 on 2026-04-17 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0010_metricadictado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEstructurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Identificador único: RODILLA, CADERA, ATM, TC_MSK, ABDOMEN C/G, TORAX S/G, etc.', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text="Nombre descriptivo para mostrar en selectores (ej. 'RM de Rodilla')", max_length=200, verbose_name='Nombre')),
                ('titulo', models.CharField(help_text="Título de la plantilla con placeholders: 'RM DE RODILLA [<DERECHA/IZQUIERDA>]'", max_length=500, verbose_name='Título')),
                ('seccion_tecnica', models.TextField(help_text='Descripción de la técnica utilizada en el estudio', verbose_name='Sección Técnica')),
                ('comentarios_base', models.JSONField(blank=True, default=list, help_text='Lista de líneas con anatomía normal que se preservan en modo ESTRUCTURADO', verbose_name='Comentarios Base')),
                ('origen', models.CharField(choices=[('legacy', 'Legado (migrado de hardcode)'), ('user', 'Creada por usuario'), ('system', 'Sistema')], default='legacy', help_text='Indica si fue migrada desde hardcode o creada por usuario', max_length=20, verbose_name='Origen')),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Solo se usan plantillas activas', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_estructuradas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla Estructurada',
                'verbose_name_plural': 'Plantillas Estructuradas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='dictado_inf_codigo_d6b024_idx'), models.Index(fields=['origen'], name='dictado_inf_origen_b40f03_idx')],
            },
        ),
    ]
