# Generated by Django 5.2.12 on 2026-04-17 00:20

from django.db import migrations


def import_plantillas_legacy(apps, schema_editor):
    """Importa plantillas desde hardcode a BD.
    
    Fuente: dictado_informes/ai_services.py improve_medical_text()
    Idempotente: no crea duplicados si la plantilla ya existe.
    """
    PlantillaEstructurada = apps.get_model('dictado_informes', 'PlantillaEstructurada')
    
    # Datos extraídos del hardcode en ai_services.py líneas 438-595
    plantillas_data = {
        'RODILLA': {
            'nombre': 'RM de Rodilla',
            'titulo': 'RM DE RODILLA [<DERECHA/IZQUIERDA>]',
            'seccion_tecnica': 'Se exploró la rodilla [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Meniscos de altura y señal normales.',
                'Ligamentos cruzados de trayecto y morfología conservados.',
                'Resto de tendones y ligamentos de la rodilla sin alteraciones.',
                'Rótula centrada, sin lesión visible.',
                'No se observa aumento del líquido articular.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'HOMBRO': {
            'nombre': 'RM de Hombro',
            'titulo': 'RM DE HOMBRO [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el hombro [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'No se observan alteraciones en los tendones que conforman el manguito rotador ni en el tendón de la porción larga del bíceps.',
                'Labrum de forma y señal normales.',
                'No se visualiza aumento del liquido articular glenohumeral ni bursal.',
                'Articulación acromioclavicular sin alteraciones.'
            ]
        },
        'CODO': {
            'nombre': 'RM de Codo',
            'titulo': 'RM DE CODO [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el codo [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Tendones epicondíleos y epitrocleares normales.',
                'Resto de tendones y ligamentos de la articulación del codo sin alteraciones.',
                'No se observa aumento del liquido articular.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'TOBILLO': {
            'nombre': 'RM de Tobillo',
            'titulo': 'RM DE TOBILLO [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el tobillo [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Tendones retromaleolares internos, retromaleolares externos y tendones flexores del pie sin alteraciones.',
                'No se observa aumento del líquido articular.',
                'Fascia plantar  y tendón de Aquiles de espesor y señal normales.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'ANTEBRAZO': {
            'nombre': 'RM de Antebrazo',
            'titulo': 'RM DE ANTEBRAZO [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el antebrazo [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Estructuras óseas del radio y cúbito sin alteraciones.',
                'Músculos del antebrazo de morfología y señal normales.',
                'Tendones flexores y extensores conservados.',
                'Nervios mediano, radial y cubital sin signos de compresión.',
                'No se observa aumento del líquido articular.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'MANO': {
            'nombre': 'RM de Mano',
            'titulo': 'RM DE MANO [<DERECHA/IZQUIERDA>]',
            'seccion_tecnica': 'Se exploró la mano [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Tendones flexores y extensores de grosor y señal conservados.',
                'Ligamentos intercarpianos sin alteraciones.',
                'Túnel carpiano de calibre normal.',
                'Nervio mediano sin compresión.',
                'Articulaciones metacarpofalángicas conservadas.',
                'No se observa aumento del líquido articular.'
            ]
        },
        'MUÑECA': {
            'nombre': 'RM de Muñeca',
            'titulo': 'RM DE MUÑECA [<DERECHA/IZQUIERDA>]',
            'seccion_tecnica': 'Se exploró la muñeca [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Fibrocartílago triangular íntegro.',
                'Tendones flexores y extensores conservados.',
                'Ligamentos escafo-lunares sin alteraciones.',
                'Túnel carpiano de calibre normal.',
                'Articulación radio-carpiana conservada.',
                'No se observa aumento del líquido articular.'
            ]
        },
        'PIE': {
            'nombre': 'RM de Pie',
            'titulo': 'RM DE PIE [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el pie [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Estructuras óseas del pie sin alteraciones.',
                'Articulaciones intertarsianas conservadas.',
                'Tendones y ligamentos sin signos de lesión.',
                'No se observa aumento del líquido articular.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'CADERA': {
            'nombre': 'RM de Cadera',
            'titulo': 'RM DE CADERA [<DERECHA/IZQUIERDA>]',
            'seccion_tecnica': 'Se exploró la cadera [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Espacio articular coxo-femoral conservado.',
                'Labrum sin alteraciones.',
                'No se visualiza aumento del líquido articular.',
                'No se observan lesiones óseas.'
            ]
        },
        'MUSLO': {
            'nombre': 'RM de Muslo',
            'titulo': 'RM DE MUSLO [<DERECHO/IZQUIERDO>]',
            'seccion_tecnica': 'Se exploró el muslo [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Músculos del muslo de morfología y señal normales.',
                'Tendones y ligamentos sin alteraciones.',
                'No se observan colecciones ni masas.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'ATM': {
            'nombre': 'RM de Articulación Temporomandibular',
            'titulo': 'RM DE ARTICULACIÓN TEMPOROMANDIBULAR [<DERECHA/IZQUIERDA>]',
            'seccion_tecnica': 'Se exploró la articulación temporomandibular [<lado>] con secuencias que ponderan tiempos de relajación T1, T2 y STIR en los diferentes planos.',
            'comentarios': [
                'Disco articular de morfología y señal normales.',
                'En fase de apertura, correcta translación del cóndilo mandibular y recaptura del disco.',
                'Músculos masticatorios sin alteraciones.',
                'Articulación sin signos de inflamación.',
                'No se visualizan lesiones óseas.'
            ]
        },
        'TC_MSK': {
            'nombre': 'TC de Musculoesquelético',
            'titulo': 'TC DE [<REGIÓN ANATÓMICA>]',
            'seccion_tecnica': 'Se realizó estudio tomográfico de la región solicitada con reconstrucciones multiplanares, sin contraste endovenoso.',
            'comentarios': [
                'Estructuras óseas de la región sin alteraciones.',
                'Articulaciones conservadas.',
                'Tejidos blandos sin signos de lesión.',
                'No se observan colecciones ni masas.',
                'No se visualizan lesiones evidentes.'
            ]
        },
        'ABDOMEN C/G': {
            'nombre': 'RM de Abdomen con Gadolinio',
            'titulo': 'RM DE ABDOMEN CON GADOLINIO',
            'seccion_tecnica': 'Se realizó resonancia magnética de abdomen y pelvis, mediante secuencias que ponderan tiempos de relajación T1 y T2 en los diferentes planos. Se inyectó gadolinio endovenoso.',
            'comentarios': [
                'Fondos de saco pleurales libres.',
                'El hígado y el bazo presentan morfología e intensidad de señal respetadas.',
                'Vesícula biliar presente, de contenido homogéneo. No se observa dilatación de la vía biliar intra ni extra hepática.',
                'Páncreas bien delimitado y sin lesión visible.',
                'Glándulas suprarrenales de configuración habitual.',
                'Ambos riñones de forma y tamaño normal, sin signos de hidronefrosis.',
                'El retroperitoneo prevertebral se halla libre de adenomegalias.',
                'No se constatan procesos expansivos ni líquido libre en cavidad al momento del examen.'
            ]
        },
        'TORAX S/G': {
            'nombre': 'RM de Tórax sin Contraste',
            'titulo': 'RM DE TÓRAX SIN CONTRASTE',
            'seccion_tecnica': 'Se realizó resonancia magnética de tórax, mediante secuencias que ponderan tiempos de relajación T1 y T2 en los diferentes planos, sin administración de contraste endovenoso.',
            'comentarios': [
                'No se identifican procesos ocupantes ni áreas de consolidación parenquimatosa, dentro de las limitaciones del método.',
                'Mediastino, hilios y axilas libres de imágenes adenomegálicas.',
                'No se observa derrame pleural ni pericárdico.'
            ]
        }
    }
    
    created_count = 0
    updated_count = 0
    
    for codigo, data in plantillas_data.items():
        obj, created = PlantillaEstructurada.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': data['nombre'],
                'titulo': data['titulo'],
                'seccion_tecnica': data['seccion_tecnica'],
                'comentarios_base': data['comentarios'],
                'origen': 'legacy',
                'activa': True,
            }
        )
        if created:
            created_count += 1
        else:
            updated_count += 1
    
    print(f"[OK] Migracion de plantillas: {created_count} creadas, {updated_count} actualizadas")


def reverse_plantillas_legacy(apps, schema_editor):
    """Reverse: elimina solo las plantillas legacy."""
    PlantillaEstructurada = apps.get_model('dictado_informes', 'PlantillaEstructurada')
    deleted_count, _ = PlantillaEstructurada.objects.filter(origen='legacy').delete()
    print(f"[WARN] Reverse: {deleted_count} plantillas legacy eliminadas")


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0011_plantillaestructurada'),
    ]

    operations = [
        migrations.RunPython(import_plantillas_legacy, reverse_plantillas_legacy),
    ]
