# Generated by Django 5.2.12 on 2026-05-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0013_plantillaestructurada_compartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaestructurada',
            name='guia_estilo',
            field=models.TextField(blank=True, default='', help_text='Instrucciones en lenguaje natural que la IA recibe para esta plantilla. Ejemplo: \'Para meniscos usar "de configuración habitual" (no "normales"). En desgarros indicar siempre grado Stoller y cuerno afectado.\'', verbose_name='Guía de Estilo'),
        ),
    ]
