# Generated by Django 5.2.12 on 2026-05-02 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0014_add_guia_estilo_to_plantilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCalidadDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('estado_feedback', models.CharField(choices=[('correcto', 'Correcto al primer intento'), ('correccion', 'Requirió corrección manual')], max_length=20, verbose_name='Resultado reportado')),
                ('modo_dictado', models.CharField(choices=[('FIEL', 'Fiel al Dictado'), ('ESTRUCTURADO', 'Plantilla Estructurada')], default='FIEL', max_length=20, verbose_name='Modo de dictado')),
                ('tipo_estudio', models.CharField(blank=True, choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo de Estudio')),
                ('tipo_plantilla', models.CharField(blank=True, max_length=50, verbose_name='Código de Plantilla')),
                ('longitud_texto_ia', models.IntegerField(default=0, verbose_name='Longitud texto IA')),
                ('longitud_texto_final', models.IntegerField(default=0, verbose_name='Longitud texto final')),
                ('caracteres_editados', models.IntegerField(default=0, verbose_name='Caracteres editados')),
                ('porcentaje_edicion', models.FloatField(default=0.0, verbose_name='Porcentaje de edición')),
                ('tuvo_edicion', models.BooleanField(default=False, verbose_name='¿Hubo edición manual?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_calidad_dictado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Feedback de Calidad de Dictado',
                'verbose_name_plural': 'Feedbacks de Calidad de Dictado',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='dictado_inf_fecha_1418c4_idx'), models.Index(fields=['usuario', '-fecha'], name='dictado_inf_usuario_55ea41_idx'), models.Index(fields=['estado_feedback', '-fecha'], name='dictado_inf_estado__af7872_idx'), models.Index(fields=['tipo_plantilla', '-fecha'], name='dictado_inf_tipo_pl_5b9545_idx')],
            },
        ),
    ]
