# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0015_add_feedback_calidad_dictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaestructurada',
            name='modo_estructura',
            field=models.CharField(
                choices=[
                    ('legacy', 'Legacy compatible'),
                    ('estricta', 'Estructura estricta'),
                    ('flexible', 'Estructura flexible'),
                    ('agente', 'Agente con confirmacion'),
                ],
                default='legacy',
                help_text='Define cuanto debe respetarse la estructura original. Legacy mantiene el comportamiento actual.',
                max_length=20,
                verbose_name='Modo de Estructura',
            ),
        ),
        migrations.AddField(
            model_name='plantillaestructurada',
            name='estructura_documento',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Representacion flexible de secciones importadas desde documentos. Si queda vacia, se deriva desde titulo, tecnica y comentarios base.',
                verbose_name='Estructura del Documento',
            ),
        ),
        migrations.AddField(
            model_name='plantillaestructurada',
            name='permitir_secciones_nuevas',
            field=models.BooleanField(
                default=False,
                help_text='Si esta desactivado, la IA no debe agregar secciones que no existan en la plantilla original.',
                verbose_name='Permitir Secciones Nuevas',
            ),
        ),
    ]
