# Generated by Django 5.2.12 on 2026-07-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0016_plantilla_estructura_flexible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaAgenteDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('huella_entrada', models.CharField(blank=True, max_length=64)),
                ('longitud_entrada', models.PositiveIntegerField(default=0)),
                ('region_detectada', models.CharField(blank=True, max_length=30)),
                ('lateralidad_detectada', models.CharField(blank=True, max_length=20)),
                ('codigo_plantilla', models.CharField(blank=True, max_length=50)),
                ('score_selector', models.IntegerField(default=0)),
                ('margen_selector', models.IntegerField(default=0)),
                ('confianza_selector', models.CharField(blank=True, max_length=10)),
                ('candidatos', models.JSONField(blank=True, default=list)),
                ('guardrails_aplicados', models.JSONField(blank=True, default=list)),
                ('confianza_ia', models.FloatField(default=0.0)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('posible_invencion', models.BooleanField(default=False)),
                ('duracion_ms', models.PositiveIntegerField(default=0)),
                ('exitosa', models.BooleanField(default=True)),
                ('error_detalle', models.CharField(blank=True, max_length=500)),
                ('plantilla_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_seleccion', to='dictado_informes.plantillaestructurada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazas_agente_dictado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traza del agente de dictado',
                'verbose_name_plural': 'Trazas del agente de dictado',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='dictado_inf_usuario_606d07_idx'), models.Index(fields=['region_detectada', '-fecha_creacion'], name='dictado_inf_region__c1308e_idx'), models.Index(fields=['exitosa', '-fecha_creacion'], name='dictado_inf_exitosa_225123_idx')],
            },
        ),
    ]
