# Generated by Django 5.2.12 on 2026-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0017_trazaagentedictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazaagentedictado',
            name='candidatos_sombra',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='codigo_plantilla_sombra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='confianza_selector_sombra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='margen_selector_sombra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='score_selector_sombra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='selector_sombra_coincide',
            field=models.BooleanField(default=False),
        ),
    ]
