# Generated by Django 5.2.12 on 2026-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0018_trazaagentedictado_candidatos_sombra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazaagentedictado',
            name='modelo_ia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
