# Generated by Django 5.2.12 on 2026-07-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0019_trazaagentedictado_modelo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazaagentedictado',
            name='codigo_plantilla_legacy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='conflicto_contexto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trazaagentedictado',
            name='origen_seleccion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
