# Generated by Django 5.2.12 on 2026-08-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0020_trazaagentedictado_codigo_plantilla_legacy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcalidaddictado',
            name='modo_dictado',
            field=models.CharField(choices=[('FIEL', 'Fiel al Dictado'), ('ESTRUCTURADO', 'Plantilla Estructurada'), ('AGENTE', 'Agente de informe')], default='FIEL', max_length=20, verbose_name='Modo de dictado'),
        ),
        migrations.CreateModel(
            name='EventoAprendizajeDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_evento', models.CharField(choices=[('plantilla_confirmada', 'Plantilla confirmada'), ('correccion_voz_aplicada', 'Correccion por voz aplicada'), ('correccion_voz_deshecha', 'Correccion por voz deshecha'), ('informe_aceptado', 'Informe aceptado'), ('informe_corregido', 'Informe que requirio correccion'), ('aprendizaje_confirmado', 'Correccion manual guardada')], max_length=40)),
                ('modo_dictado', models.CharField(blank=True, max_length=20)),
                ('tipo_estudio', models.CharField(blank=True, choices=[('RES', 'Resonancia Magnética'), ('TOM', 'Tomografía'), ('RAD', 'Radiografía'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('DEN', 'Densitometría'), ('OTR', 'Otro')], max_length=3)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('modalidad', models.CharField(blank=True, max_length=20)),
                ('lateralidad', models.CharField(blank=True, max_length=20)),
                ('plantilla_propuesta_codigo', models.CharField(blank=True, max_length=50)),
                ('plantilla_confirmada_codigo', models.CharField(blank=True, max_length=50)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('revertido', models.BooleanField(default=False)),
                ('correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='dictado_informes.correccionaprendizaje')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='dictado_informes.feedbackcalidaddictado')),
                ('traza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='dictado_informes.trazaagentedictado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_aprendizaje_dictado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de aprendizaje de dictado',
                'verbose_name_plural': 'Eventos de aprendizaje de dictado',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'tipo_evento', '-fecha'], name='dictado_inf_usuario_7124f1_idx'), models.Index(fields=['region', 'modalidad', '-fecha'], name='dictado_inf_region_7fc235_idx'), models.Index(fields=['plantilla_confirmada_codigo', '-fecha'], name='dictado_inf_plantil_e75ef8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAprendidaDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('seleccion_plantilla', 'Seleccion de plantilla'), ('terminologia', 'Terminologia'), ('orden', 'Orden de hallazgos'), ('estructura', 'Estructura del informe'), ('conclusion', 'Conclusion')], max_length=30)),
                ('clave', models.CharField(max_length=180)),
                ('valor', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('candidata', 'Candidata'), ('activa', 'Activa'), ('inactiva', 'Inactiva'), ('reemplazada', 'Reemplazada')], default='candidata', max_length=20)),
                ('vigente', models.BooleanField(default=True)),
                ('cantidad_evidencia', models.PositiveIntegerField(default=0)),
                ('confirmaciones', models.PositiveIntegerField(default=0)),
                ('rechazos', models.PositiveIntegerField(default=0)),
                ('confianza', models.FloatField(default=0.0)),
                ('origen', models.CharField(choices=[('automatico', 'Automatico'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_siguientes', to='dictado_informes.preferenciaaprendidadictado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_aprendidas_dictado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia aprendida de dictado',
                'verbose_name_plural': 'Preferencias aprendidas de dictado',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['usuario', 'categoria', 'vigente'], name='dictado_inf_usuario_7fdbed_idx'), models.Index(fields=['estado', '-fecha_modificacion'], name='dictado_inf_estado_e68e05_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'categoria', 'clave', 'version'), name='uniq_preferencia_dictado_version')],
            },
        ),
    ]
