# Generated by Django 5.2.12 on 2026-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado_informes', '0021_alter_feedbackcalidaddictado_modo_dictado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correccionaprendizaje',
            name='lateralidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='correccionaprendizaje',
            name='modalidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='correccionaprendizaje',
            name='modo_dictado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='correccionaprendizaje',
            name='region',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='correccionaprendizaje',
            name='tipo_plantilla',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
