# Generated by Django 5.2.12 on 2026-03-24 20:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Anticipo primera vivienda', max_length=200, verbose_name='Nombre del proyecto')),
                ('meta_usd', models.DecimalField(decimal_places=2, help_text='Monto total objetivo en dólares', max_digits=12, verbose_name='Meta en USD')),
                ('fecha_objetivo', models.DateField(blank=True, help_text='Fecha estimada para alcanzar la meta (opcional)', null=True, verbose_name='Fecha objetivo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Meta',
                'verbose_name_plural': 'Configuración de Meta',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('blue_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Blue compra')),
                ('blue_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Blue venta')),
                ('oficial_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Oficial compra')),
                ('oficial_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Oficial venta')),
                ('mep', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MEP')),
                ('eur_usd', models.DecimalField(decimal_places=4, default=Decimal('1.0800'), help_text='Tipo de cambio Euro a Dólar (ej: 1.08)', max_digits=10, verbose_name='EUR/USD')),
                ('fuente', models.CharField(choices=[('api', 'API Bluelytics'), ('manual', 'Manual')], default='manual', max_length=10, verbose_name='Fuente')),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('descripcion', models.CharField(help_text='Ej: Compra USD en cueva, Transferencia a cuenta exterior', max_length=300, verbose_name='Descripción')),
                ('moneda_origen', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)'), ('BRL', 'Reales (BRL)'), ('otro', 'Otra moneda')], max_length=10, verbose_name='Moneda origen')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto origen')),
                ('moneda_destino', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)'), ('BRL', 'Reales (BRL)'), ('otro', 'Otra moneda')], max_length=10, verbose_name='Moneda destino')),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto destino')),
                ('cotizacion_efectiva', models.DecimalField(decimal_places=4, help_text='Tipo de cambio real al que se realizó la operación', max_digits=10, verbose_name='Cotización efectiva')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversiones_vivienda', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('cotizacion_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversiones', to='ahorro_vivienda.cotizacion', verbose_name='Cotización de referencia')),
            ],
            options={
                'verbose_name': 'Conversión',
                'verbose_name_plural': 'Conversiones',
                'ordering': ['-fecha', '-creada'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('total_usd_calculado', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma de todos los ítems convertidos a USD', max_digits=14, verbose_name='Total en USD')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='ahorro_vivienda.cotizacion', verbose_name='Cotización utilizada')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_vivienda', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Snapshot de Capital',
                'verbose_name_plural': 'Snapshots de Capital',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CapitalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Efectivo USD, Cuenta Galicia, Mercado Pago', max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera_virtual', 'Billetera Virtual'), ('cripto', 'Criptomonedas'), ('otro', 'Otro')], default='efectivo', max_length=30, verbose_name='Tipo de activo')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)'), ('BRL', 'Reales (BRL)'), ('otro', 'Otra moneda')], default='ARS', max_length=10, verbose_name='Moneda')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto original')),
                ('cotizacion_tipo', models.CharField(choices=[('blue_venta', 'Dólar Blue (venta)'), ('blue_compra', 'Dólar Blue (compra)'), ('oficial_venta', 'Dólar Oficial (venta)'), ('oficial_compra', 'Dólar Oficial (compra)'), ('mep', 'Dólar MEP'), ('manual', 'Cotización manual'), ('uno_a_uno', '1:1 (ya está en USD)')], default='blue_venta', help_text='Cómo convertir a USD', max_length=20, verbose_name='Cotización a usar')),
                ('cotizacion_manual', models.DecimalField(blank=True, decimal_places=4, help_text='Solo si elegiste "cotización manual"', max_digits=10, null=True, verbose_name='Cotización manual')),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Equivalente en USD')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ahorro_vivienda.snapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Ítem de Capital',
                'verbose_name_plural': 'Ítems de Capital',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
