# Generated by Django 5.1.4 on 2025-04-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('cancelado', 'Estudio cancelado'), ('demorado', 'Estudio demorado'), ('pendiente', 'Estudio pendiente'), ('tecnico', 'Problema técnico'), ('conflicto', 'Conflicto o situación interpersonal'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado')], default='abierto', max_length=20)),
                ('nombre_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio_relacionado', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evento', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion_eventos.eventoservicio')),
            ],
        ),
    ]
