# Generated by Django 5.1.4 on 2025-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoservicio',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
