# Generated by Django 5.1.4 on 2025-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0002_eventoservicio_dni_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoservicio',
            name='sector_de_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
