# Generated by Django 5.1.4 on 2025-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0003_eventoservicio_sector_de_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoservicio',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='abierto', max_length=20),
        ),
    ]
