# Generated by Django 5.1.4 on 2025-05-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0004_alter_eventoservicio_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_eventos.eventoservicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
