# Generated by Django 5.1.4 on 2025-05-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0005_historialevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoservicio',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto')], default='abierto', max_length=20),
        ),
    ]
