# Generated by Django 5.1.4 on 2025-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0006_alter_eventoservicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoservicio',
            name='servicio_origen_evento',
            field=models.CharField(blank=True, choices=[('tomografia', 'Tomografía'), ('resonancia', 'Resonancia'), ('ecografia', 'Ecografía'), ('radiologia', 'Radiología')], max_length=20, null=True),
        ),
    ]
