# Generated by Django 5.1.4 on 2025-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_eventos', '0007_eventoservicio_servicio_origen_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoservicio',
            name='tipo_evento',
            field=models.CharField(choices=[('cancelado', 'Estudio cancelado'), ('demorado', 'Estudio demorado'), ('pendiente', 'Estudio pendiente'), ('tecnico', 'Problema técnico'), ('conflicto', 'Conflicto o situación interpersonal'), ('guardia', 'Estudio de guardia realizado'), ('internado', 'Estudio de paciente internado realizado'), ('otro', 'Otro')], max_length=20),
        ),
    ]
